/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.ProductionMgr;

import Business.Ecosystem.Ecosystem;
import Business.Organization.ProductionOrganization;
import Business.User.User;
import Business.WorkTaskQueue.BuildCarTask;
import Business.Ecosystem.Network;
import Business.Enterprise.DealershipEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.LogisticsOrganization;
import Business.Organization.Organization;
import Business.Organization.WarehousingOrganization;
import Business.WorkTaskQueue.GetPartTask;
import Business.WorkTaskQueue.WorkTask;
import Business.WorkTaskQueue.VehicleDeliveryTask;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Roles.ProductionManager;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
/**
 *
 * @author Meredith Molyneux
 * @author Nicholas Woodward
 */
public class NewOrderJPanel extends javax.swing.JPanel {
                  // ATTRIBUTES
    ProductionOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    BuildCarTask task;

    /**
     * Creates new form NewOrderJPanel
     */
    public NewOrderJPanel(JPanel csp, User usr, ProductionOrganization org, Ecosystem system, BuildCarTask tsk) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        this.task = tsk;
        initComponents();
        buildProductionOrderScreen();
          lblTitle.setText(this.organization.getName() + " - Custom Car Order");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
 * Builds the Production work screen for a dealership custom vehicle order.
 */
private void buildProductionOrderScreen() {
    removeAll();
    setLayout(new BorderLayout());

    JPanel headerPanel = new JPanel(new BorderLayout());
    headerPanel.setBackground(new Color(76, 47, 112));
    headerPanel.setBorder(new EmptyBorder(16, 20, 16, 20));

    JLabel titleLabel = new JLabel("German Production — Vehicle Build");
    titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 22));
    titleLabel.setForeground(Color.WHITE);
    titleLabel.setHorizontalAlignment(SwingConstants.CENTER);

    JLabel orderLabel = new JLabel(task.toString());
    orderLabel.setForeground(new Color(235, 220, 250));
    orderLabel.setHorizontalAlignment(SwingConstants.CENTER);

    headerPanel.add(titleLabel, BorderLayout.NORTH);
    headerPanel.add(orderLabel, BorderLayout.SOUTH);

    JLabel instructionsLabel = new JLabel(
            "Complete the vehicle build after required components are available.");
    instructionsLabel.setHorizontalAlignment(SwingConstants.CENTER);
    instructionsLabel.setBorder(new EmptyBorder(30, 20, 30, 20));

    JButton completeBuildButton = new JButton("Complete Vehicle Build");
    completeBuildButton.addActionListener(event -> completeVehicleBuild());

    JPanel buttonPanel = new JPanel();
    buttonPanel.add(completeBuildButton);

    add(headerPanel, BorderLayout.NORTH);
    add(instructionsLabel, BorderLayout.CENTER);
    add(buttonPanel, BorderLayout.SOUTH);

    revalidate();
    repaint();
}
/**
 * Confirms that Supplier Warehouse completed the components request linked
 * to this customer vehicle order before Production finishes the build.
 *
 * @return true when required components are available for this build
 */
private boolean componentsAreReady() {
    if (task.getCustomOrder() == null) {
        return true;
    }

    String orderId = task.getCustomOrder().getOrderId();

    for (Network network : business.getNetworks()) {
        for (Enterprise enterprise
                : network.getEnterprises().getEnterprises()) {
            for (Organization org
                    : enterprise.getOrganizations().getOrganizations()) {

                if (!(org instanceof WarehousingOrganization)) {
                    continue;
                }

                for (WorkTask workTask
                        : org.getOutTasks().getTasks()) {

                    if (workTask instanceof GetPartTask) {
                        GetPartTask partTask = (GetPartTask) workTask;

                        if (partTask.getCustomOrder() != null
                                && orderId.equals(
                                        partTask.getCustomOrder()
                                                .getOrderId())
                                && partTask.isCompleted()) {
                            return true;
                        }
                    }
                }
            }
        }
    }

    return false;
}
/**
 * Completes the Production build and sends the finished vehicle to
 * Manufacturer Logistics for cross-enterprise delivery to the dealership.
 */
private void completeVehicleBuild() {
    if (task.isCompleted()) {
        JOptionPane.showMessageDialog(
                this,
                "This vehicle build has already been completed.",
                "Build Complete",
                JOptionPane.INFORMATION_MESSAGE);
        return;
    }
        if (!componentsAreReady()) {
        JOptionPane.showMessageDialog(
                this,
                "Supplier Warehouse must complete the required "
                        + "components request before Production can "
                        + "complete this vehicle.",
                "Components Not Ready",
                JOptionPane.WARNING_MESSAGE);
        return;
    }
    LogisticsOrganization logisticsOrganization = null;
    DealershipEnterprise dealership = null;

    for (Network network : business.getNetworks()) {
        for (Enterprise enterprise
                : network.getEnterprises().getEnterprises()) {

            if (enterprise instanceof DealershipEnterprise) {
                dealership = (DealershipEnterprise) enterprise;
            }

            for (Organization org
                    : enterprise.getOrganizations().getOrganizations()) {
                if (org instanceof LogisticsOrganization) {
                    logisticsOrganization = (LogisticsOrganization) org;
                }
            }
        }
    }

    if (logisticsOrganization == null || dealership == null) {
        JOptionPane.showMessageDialog(
                this,
                "Unable to locate Logistics or the Dealership destination.",
                "Delivery Setup Error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    VehicleDeliveryTask deliveryTask = new VehicleDeliveryTask(
            user,
            task.getCustomOrder(),
            dealership);

    logisticsOrganization.getInTasks().pushTask(deliveryTask);
    organization.getOutTasks().pushTask(deliveryTask);

    task.Complete();
    organization.getInTasks().popTask(task);
    organization.getOutTasks().pushTask(task);

    if (user.getRole() instanceof ProductionManager) {
        ProductionManager productionManager
                = (ProductionManager) user.getRole();
        productionManager.setCurrentTask(null);
    }

    JOptionPane.showMessageDialog(
            this,
            "Vehicle build completed. A delivery task was sent to "
                    + "Manufacturer Logistics for "
                    + dealership.getName() + ".");

    workArea.remove(this);
    ((CardLayout) workArea.getLayout()).previous(workArea);
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack1 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 153, 255));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(650, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack1.setText("<<< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 130, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Custom Car Order");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 660, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
