/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.ProductionMgr;

import Business.Ecosystem.Ecosystem;
import Business.Organization.ProductionOrganization;
import Business.User.User;
import Business.WorkTaskQueue.BuildCarTask;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Meredith Molyneux
 */
public class NewOrderJPanel extends javax.swing.JPanel {
                  // ATTRIBUTES
    ProductionOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    BuildCarTask task;

    /**
     * Creates new form NewOrderJPanel
     */
    public NewOrderJPanel(JPanel csp, User usr, ProductionOrganization org, Ecosystem system, BuildCarTask tsk) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        this.task = tsk;
        initComponents();
          lblTitle.setText(this.organization.getName() + " - Custom Car Order");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack1 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 153, 255));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(650, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack1.setText("<<< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 130, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Custom Car Order");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 660, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
