/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.LogisticsCoordinator;

import Business.Ecosystem.Ecosystem;
import Business.Enterprise.SupplierEnterprise;
import Business.Organization.LogisticsOrganization;
import Business.Roles.LogisticsCoordinator;
import Business.User.User;
import Business.Vehicle.Part;
import Business.WorkTaskQueue.ProcessShipmentTask;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ajay Alamuri
 */
public class ProcessShipmentJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    LogisticsOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    ProcessShipmentTask task;
    
    /**
     * Creates new form ProcessShipmentJPanel
     */
    public ProcessShipmentJPanel(JPanel csp, User usr, LogisticsOrganization org, Ecosystem system, ProcessShipmentTask tsk) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        this.task = tsk;
        
        initComponents();
        lblTitle.setText(organization.getName() + " Incoming Shipment Processing");
        
        refreshFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPart = new javax.swing.JLabel();
        txtPart = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnComplete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setPreferredSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Incoming Shipment Processing");
        lblTitle.setMaximumSize(new java.awt.Dimension(650, 600));
        lblTitle.setMinimumSize(new java.awt.Dimension(650, 600));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        lblPart.setText("Part:");
        add(lblPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 40, -1));

        txtPart.setEditable(false);
        add(txtPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 160, -1));

        lblStock.setText("Current Stock:");
        add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 90, -1));

        txtStock.setEditable(false);
        add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 160, -1));

        lblQuantity.setText("Incoming Quantity:");
        add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 120, -1));
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 160, -1));

        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });
        add(btnComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 90, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to previous page
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // Add new stock to company database
        
        // Validate if task still needs to be complete
        if (task.isCompleted()) {
            JOptionPane.showMessageDialog(null, "Task has already been completed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Field validation
        String strQuantity = txtQuantity.getText();
        if (strQuantity.isBlank()) {
            JOptionPane.showMessageDialog(null, "Incoming quantity cannot be blank.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int quantity = -1;
        try {
            quantity = Integer.parseInt(strQuantity);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Incoming quantity must be an integer.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (quantity < 0) {
            JOptionPane.showMessageDialog(null, "Incoming quantity cannot be less than 0.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Update in backend
        SupplierEnterprise company = (SupplierEnterprise) organization.getCompany();
        Part part = task.getPart();
        int oldQuantity = company.getPartQuantity(part);
        company.setPartQuantity(part, oldQuantity + quantity);
        
        // Update task status
        organization.getInTasks().popTask(task);
        organization.getOutTasks().pushTask(task);
        ((LogisticsCoordinator) user.getRole()).completeTask();
        
        // Notify and refresh
        JOptionPane.showMessageDialog(null, "Shipment successfully processed, please return and track a new task.", "Success", JOptionPane.INFORMATION_MESSAGE);
        refreshFields();
    }//GEN-LAST:event_btnCompleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnComplete;
    private javax.swing.JLabel lblPart;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtPart;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

    private void refreshFields() {
        txtPart.setText(task.getPart().toString());
        txtStock.setText(String.valueOf(((SupplierEnterprise) organization.getCompany()).getPartQuantity(task.getPart())));
        txtQuantity.setText("");
    }
}
