/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.LogisticsCoordinator;

import Business.Ecosystem.Ecosystem;
import Business.Ecosystem.Network;
import Business.Enterprise.DealershipEnterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Enterprise.ManufacturerEnterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Organization.LogisticsOrganization;
import Business.User.User;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ajay Alamuri
 */
public class ViewNetworkJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    LogisticsOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    
    /**
     * Creates new form ViewNetworkJPanel
     */
    public ViewNetworkJPanel(JPanel csp, User usr, LogisticsOrganization org, Ecosystem system) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        
        initComponents();
        
        refreshTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManufacturers = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDealerships = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSuppliers = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 153, 255));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("Network Map");
        lblTitle.setMaximumSize(new java.awt.Dimension(650, 600));
        lblTitle.setMinimumSize(new java.awt.Dimension(650, 600));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 130, -1));

        tblManufacturers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Manufacturers"
            }
        ));
        jScrollPane1.setViewportView(tblManufacturers);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 200, -1));

        tblDealerships.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Dealerships"
            }
        ));
        jScrollPane2.setViewportView(tblDealerships);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, -1));

        tblSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Suppliers"
            }
        ));
        jScrollPane3.setViewportView(tblSuppliers);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to previous page
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblDealerships;
    private javax.swing.JTable tblManufacturers;
    private javax.swing.JTable tblSuppliers;
    // End of variables declaration//GEN-END:variables

    private void refreshTables() {
        refreshManufacturers();
        refreshDealerships();
        refreshSuppliers();
    }

    private void refreshManufacturers() {
        DefaultTableModel model = (DefaultTableModel) tblManufacturers.getModel();
        
        model.setRowCount(0);
        
        for (Network net : business.getNetworks()) {
            EnterpriseDirectory ed = net.getEnterprises();
            if (ed.findEnterprise(organization.getCompany().getID()) != null) {
                for (ManufacturerEnterprise me : ed.getManufacturers()) {
                    Object[] row = new Object[1];
                    
                    row[0] = me;
                    
                    model.addRow(row);
                }
            }
        }
    }

    private void refreshDealerships() {
        DefaultTableModel model = (DefaultTableModel) tblDealerships.getModel();
        
        model.setRowCount(0);
        
        for (Network net : business.getNetworks()) {
            EnterpriseDirectory ed = net.getEnterprises();
            if (ed.findEnterprise(organization.getCompany().getID()) != null) {
                for (DealershipEnterprise de : ed.getDealerships()) {
                    Object[] row = new Object[1];
                    
                    row[0] = de;
                    
                    model.addRow(row);
                }
            }
        }
    }

    private void refreshSuppliers() {
        DefaultTableModel model = (DefaultTableModel) tblSuppliers.getModel();
        
        model.setRowCount(0);
        
        for (Network net : business.getNetworks()) {
            EnterpriseDirectory ed = net.getEnterprises();
            if (ed.findEnterprise(organization.getCompany().getID()) != null) {
                for (SupplierEnterprise se : ed.getSuppliers()) {
                    Object[] row = new Object[1];
                    
                    row[0] = se;
                    
                    model.addRow(row);
                }
            }
        }
    }

    
}
