/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas;

import Business.Ecosystem.Ecosystem;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.User.User;
import UserInterface.Admin.ManageOrganizations;
import UserInterface.Admin.MyProfileJPanel;
import UserInterface.Admin.ViewNetworkJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ajay Alamuri
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    AdminOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel csp, User usr, Organization org, Ecosystem system) {
        this.organization = (AdminOrganization) org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        
        initComponents();
        lblTitle.setText(this.organization.getCompany().getName() + " - " + this.organization.getName());
        lblWelcome.setText("Welcome " + this.user.getEmployee().getPerson().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnEmployees = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        btnOrganizations = new javax.swing.JButton();
        btnNetwork = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setPreferredSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblWelcome.setText("Welcome <User>");
        add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 460, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Company Name> <Org Name>");
        lblTitle.setMaximumSize(new java.awt.Dimension(650, 600));
        lblTitle.setMinimumSize(new java.awt.Dimension(650, 600));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        btnEmployees.setText("Manage Employees");
        btnEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeesActionPerformed(evt);
            }
        });
        add(btnEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 160, 80));

        btnUsers.setText("Manage User Accounts");
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        add(btnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 160, 80));

        btnOrganizations.setText("Manage Organizations");
        btnOrganizations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizationsActionPerformed(evt);
            }
        });
        add(btnOrganizations, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 170, 80));

        btnNetwork.setText("View Network");
        btnNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetworkActionPerformed(evt);
            }
        });
        add(btnNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 160, 80));

        btnMyProfile.setText("My Profile");
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileActionPerformed(evt);
            }
        });
        add(btnMyProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 160, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmployeesActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnOrganizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizationsActionPerformed
        // TODO add your handling code here:
        ManageOrganizations mojp = new ManageOrganizations(workArea, user, organization, business);
        this.workArea.add(mojp, "ManageOrganizations");
        ((CardLayout) this.workArea.getLayout()).next(workArea);
    }//GEN-LAST:event_btnOrganizationsActionPerformed

    private void btnNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetworkActionPerformed
        // TODO add your handling code here:
        ViewNetworkJPanel vnjp = new ViewNetworkJPanel(workArea, user, organization, business);
        this.workArea.add(vnjp, "ViewNetwork");
        ((CardLayout) this.workArea.getLayout()).next(workArea);
    }//GEN-LAST:event_btnNetworkActionPerformed

    private void btnMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileActionPerformed
        // TODO add your handling code here:
        MyProfileJPanel mpjp = new MyProfileJPanel(workArea, user, organization, business);
        this.workArea.add(mpjp, "MyProfile");
        ((CardLayout) this.workArea.getLayout()).next(workArea);
    }//GEN-LAST:event_btnMyProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployees;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnNetwork;
    private javax.swing.JButton btnOrganizations;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
