/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas;

import Business.Ecosystem.Ecosystem;
import Business.Organization.Organization;
import Business.User.User;
import Business.Vehicle.CustomVehicleOrder;
import Business.WorkTaskQueue.SellVehicleTask;
import Business.WorkTaskQueue.WorkTask;
import Business.Ecosystem.Network;
import Business.Enterprise.Enterprise;
import Business.Organization.ServiceOrganization;
import Business.WorkTaskQueue.ServiceAppointmentTask;
import Business.Enterprise.DealershipEnterprise;
import Business.WorkTaskQueue.TradeInTask;
import java.awt.GridLayout;
import javax.swing.JOptionPane;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.JPanel;

/**
 *
 * @author Ajay Alamuri
 * @author nicholaswoodward
 */
public class CustomerServiceRepresentativeWorkAreaJPanel extends javax.swing.JPanel {
    // Toyota Sales organization containing customer custom-order records.
    private Organization salesOrganization;
    // Gives Customer Service access to the dealership Service Center.
    private Ecosystem ecosystem;
    private User customerServiceRepresentative;
    private JTextField serviceVinField;
    // VIN field used when a customer requests a trade-in evaluation.
    private JTextField tradeInVinField;    
    // Customer-support order table and its searchable data model.
    private DefaultTableModel tableModel;
    private JTable ordersTable;
    private JTextField searchField;
    /**
     * Creates new form CustomerServiceWorkAreaJPanel
     */
    public CustomerServiceRepresentativeWorkAreaJPanel(JPanel csp, User usr, Organization org, Ecosystem system) {
        initComponents();
        this.ecosystem = system;
        this.customerServiceRepresentative = usr; 
        buildCustomerSupportScreen(org);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * Builds the Customer Service portal for searching and tracking
     * dealership custom vehicle orders.
     *
     * @param organization Toyota Sales organization containing customer orders
     */
    private void buildCustomerSupportScreen(Organization organization) {
        salesOrganization = organization;

        removeAll();
        setLayout(new BorderLayout(10, 10));
        setBorder(new EmptyBorder(14, 14, 14, 14));
        setBackground(new Color(245, 247, 250));

        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setBackground(new Color(20, 80, 130));
        headerPanel.setBorder(new EmptyBorder(16, 20, 16, 20));

        JLabel titleLabel = new JLabel(
        organization.getCompany().getName()
        + " - "
        + organization.getName());
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 22));
        titleLabel.setForeground(Color.WHITE);
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);

        JLabel subtitleLabel = new JLabel(
        "Welcome "
        + customerServiceRepresentative.getEmployee()
                .getPerson().getName()
        + " | Customer orders, service appointments, and trade-ins");
        subtitleLabel.setForeground(new Color(220, 235, 250));
        subtitleLabel.setHorizontalAlignment(SwingConstants.CENTER);

        headerPanel.add(titleLabel, BorderLayout.NORTH);
        headerPanel.add(subtitleLabel, BorderLayout.SOUTH);
        add(headerPanel, BorderLayout.NORTH);

        JPanel supportPanel = new JPanel(new BorderLayout(8, 8));
        supportPanel.setBackground(Color.WHITE);
        supportPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
                "Customer Order Lookup"));

        JPanel searchPanel = new JPanel();
        searchPanel.setBackground(Color.WHITE);

        searchField = new JTextField(22);
        JButton searchButton = new JButton("Search");
        JButton showAllButton = new JButton("Show All Orders");

        searchButton.addActionListener(event ->
                populateCustomerOrders(searchField.getText()));

        showAllButton.addActionListener(event -> {
            searchField.setText("");
            populateCustomerOrders("");
        });

        searchPanel.add(new JLabel("Order ID, Customer, or Status:"));
        searchPanel.add(searchField);
        searchPanel.add(searchButton);
        searchPanel.add(showAllButton);

        tableModel = new DefaultTableModel(
                new String[]{
                    "Order ID",
                    "Customer",
                    "Email",
                    "Vehicle",
                    "VIN",
                    "Deposit",
                    "Current Status"
                }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ordersTable = new JTable(tableModel);
        ordersTable.setAutoCreateRowSorter(true);
        ordersTable.getSelectionModel().addListSelectionListener(event -> {
        if (!event.getValueIsAdjusting()) {
        copySelectedVinToAfterSalesFields();
    }
});
        JLabel supportMessage = new JLabel(
                "Customer Service can search order records and provide "
                + "accurate international fulfillment updates.");

        supportPanel.add(searchPanel, BorderLayout.NORTH);
        supportPanel.add(new JScrollPane(ordersTable), BorderLayout.CENTER);
        JPanel bottomPanel = new JPanel(new BorderLayout(0, 10));
            bottomPanel.setOpaque(false);
            bottomPanel.add(supportMessage, BorderLayout.NORTH);
            bottomPanel.add(buildAppointmentPanel(), BorderLayout.SOUTH);

supportPanel.add(bottomPanel, BorderLayout.SOUTH);

        add(supportPanel, BorderLayout.CENTER);

        populateCustomerOrders("");
        revalidate();
        repaint();
    }

    /**
     * Loads dealership customer orders that match the optional search text.
     *
     * @param searchText order ID, customer name, or status to search for
     */
    private void populateCustomerOrders(String searchText) {
        tableModel.setRowCount(0);
        String filter = searchText == null
                ? ""
                : searchText.trim().toLowerCase();

        for (WorkTask workTask : salesOrganization.getOutTasks().getTasks()) {
            if (workTask instanceof SellVehicleTask) {
                SellVehicleTask salesTask = (SellVehicleTask) workTask;
                CustomVehicleOrder order = salesTask.getCustomOrder();

                if (order != null && matchesSearch(
                        order, salesTask, filter)) {
                    tableModel.addRow(new Object[]{
                        order.getOrderId(),
                        order.getCustomerName(),
                        order.getCustomerEmail(),
                        order.getVehicleDescription(),
                        order.getVehicleVin(),
                        String.format("$%,.2f", order.getDepositPaid()),
                        salesTask.getStatus()
                    });
                }
            }
        }
    }

    /**
     * Checks whether an order matches a Customer Service search.
     *
     * @param order dealership custom vehicle order
     * @param salesTask order workflow task
     * @param filter normalized user search text
     * @return true when the order should appear in the lookup table
     */
    private boolean matchesSearch(
            CustomVehicleOrder order,
            SellVehicleTask salesTask,
            String filter) {

        return filter.isEmpty()
                || order.getOrderId().toLowerCase().contains(filter)
                || order.getCustomerName().toLowerCase().contains(filter)
                || String.valueOf(order.getVehicleVin()).contains(filter)
                || salesTask.getStatus().toString()
                        .toLowerCase().contains(filter);
    }
/**
 * Copies the VIN from a selected delivered order into both after-sales forms.
 * Vehicles that are still in production or transit cannot be serviced yet.
 */
private void copySelectedVinToAfterSalesFields() {
    int selectedRow = ordersTable.getSelectedRow();

    if (selectedRow < 0
            || serviceVinField == null
            || tradeInVinField == null) {
        return;
    }

    int modelRow = ordersTable.convertRowIndexToModel(selectedRow);
    String status = String.valueOf(tableModel.getValueAt(modelRow, 6));

    if (!"DELIVERED".equals(status)) {
        serviceVinField.setText("");
        tradeInVinField.setText("");
        return;
    }

    String vin = String.valueOf(tableModel.getValueAt(modelRow, 4));
    serviceVinField.setText(vin);
    tradeInVinField.setText(vin);
}    
/**
 * Confirms that a VIN belongs to a vehicle already delivered to this
 * dealership before Customer Service creates an after-sales request.
 *
 * @param vin VIN requested for service or trade-in
 * @return true when the delivered vehicle exists in dealership records
 */
private boolean isDeliveredDealershipVehicle(int vin) {
    if (!(salesOrganization.getCompany() instanceof DealershipEnterprise)) {
        return false;
    }

    DealershipEnterprise dealership
            = (DealershipEnterprise) salesOrganization.getCompany();

    return dealership.findAutomobileByVin(vin) != null;
}
/**
 * Builds Customer Service actions for appointments and trade-in requests.
 *
 * @return panel containing dealership after-sales actions
 */
private JPanel buildAppointmentPanel() {
    JPanel afterSalesPanel = new JPanel(new GridLayout(2, 1, 0, 8));
    afterSalesPanel.setOpaque(false);

    JPanel appointmentPanel = new JPanel(new BorderLayout(10, 0));
    appointmentPanel.setBackground(new Color(235, 242, 250));
    appointmentPanel.setBorder(new EmptyBorder(10, 10, 10, 10));

    JLabel appointmentLabel = new JLabel(
            "Book Service Appointment — Vehicle VIN:");
    serviceVinField = new JTextField();

    JButton bookAppointmentButton = new JButton("Send to Service Center");
    bookAppointmentButton.addActionListener(event -> bookServiceAppointment());

    appointmentPanel.add(appointmentLabel, BorderLayout.WEST);
    appointmentPanel.add(serviceVinField, BorderLayout.CENTER);
    appointmentPanel.add(bookAppointmentButton, BorderLayout.EAST);

    JPanel tradeInPanel = new JPanel(new BorderLayout(10, 0));
    tradeInPanel.setBackground(new Color(245, 239, 222));
    tradeInPanel.setBorder(new EmptyBorder(10, 10, 10, 10));

    JLabel tradeInLabel = new JLabel(
            "Request Trade-In Evaluation — Vehicle VIN:");
    tradeInVinField = new JTextField();

    JButton tradeInButton = new JButton("Send Trade-In to Service Center");
    tradeInButton.addActionListener(event -> bookTradeInEvaluation());

    tradeInPanel.add(tradeInLabel, BorderLayout.WEST);
    tradeInPanel.add(tradeInVinField, BorderLayout.CENTER);
    tradeInPanel.add(tradeInButton, BorderLayout.EAST);

    afterSalesPanel.add(appointmentPanel);
    afterSalesPanel.add(tradeInPanel);

    return afterSalesPanel;
}

/**
 * Creates a service appointment from Customer Service and routes it to the
 * dealership Service Center work queue.
 */
private void bookServiceAppointment() {
    String vinText = serviceVinField.getText().trim();

    if (!vinText.matches("\\d+")) {
        JOptionPane.showMessageDialog(
                this,
                "Enter a numeric VIN before booking the appointment.",
                "Invalid VIN",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    ServiceOrganization serviceCenter = findServiceOrganization();

    if (serviceCenter == null) {
        JOptionPane.showMessageDialog(
                this,
                "The dealership Service Center could not be found.",
                "Service Center Unavailable",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int vin = Integer.parseInt(vinText);
if (!isDeliveredDealershipVehicle(vin)) {
    JOptionPane.showMessageDialog(
            this,
            "Select a vehicle that has been delivered to the dealership.",
            "Vehicle Not Available for Service",
            JOptionPane.WARNING_MESSAGE);
    return;
}
        ServiceAppointmentTask appointment
                = salesOrganization.getOutTasks().createServiceAppointmentTask(
                        customerServiceRepresentative, vin);

        serviceCenter.getInTasks().pushTask(appointment);
        if (salesOrganization.getCompany() instanceof DealershipEnterprise) {
            DealershipEnterprise dealership
                    = (DealershipEnterprise) salesOrganization.getCompany();
            dealership.addServiceRecord(appointment);
        }
        JOptionPane.showMessageDialog(
                this,
                "Service appointment for VIN " + vin
                + " was sent to " + serviceCenter.getName() + ".");

        serviceVinField.setText("");
    } catch (Exception exception) {
        JOptionPane.showMessageDialog(
                this,
                exception.getMessage(),
                "Appointment Not Created",
                JOptionPane.ERROR_MESSAGE);
    }
}

/**
 * Finds the Service Center organization within the current dealership.
 *
 * @return dealership service organization, or null when unavailable
 */
/**
 * Sends a customer trade-in evaluation request to the Service Center.
 */
private void bookTradeInEvaluation() {
    String vinText = tradeInVinField.getText().trim();

    if (!vinText.matches("\\d+")) {
        JOptionPane.showMessageDialog(
                this,
                "Enter a numeric VIN before requesting a trade-in evaluation.",
                "Invalid VIN",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    ServiceOrganization serviceCenter = findServiceOrganization();

    if (serviceCenter == null) {
        JOptionPane.showMessageDialog(
                this,
                "The dealership Service Center could not be found.",
                "Service Center Unavailable",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int vin = Integer.parseInt(vinText);
if (!isDeliveredDealershipVehicle(vin)) {
    JOptionPane.showMessageDialog(
            this,
            "Select a vehicle that has been delivered to the dealership.",
            "Vehicle Not Available for Trade-In",
            JOptionPane.WARNING_MESSAGE);
    return;
}
        TradeInTask tradeIn
                = serviceCenter.getInTasks().createTradeInTask(
                        customerServiceRepresentative, vin);

        salesOrganization.getOutTasks().pushTask(tradeIn);

        if (salesOrganization.getCompany() instanceof DealershipEnterprise) {
            DealershipEnterprise dealership
                    = (DealershipEnterprise) salesOrganization.getCompany();
            dealership.addServiceRecord(tradeIn);
        }

        JOptionPane.showMessageDialog(
                this,
                "Trade-in evaluation for VIN " + vin
                + " was sent to " + serviceCenter.getName() + ".");

        tradeInVinField.setText("");

    } catch (Exception exception) {
        JOptionPane.showMessageDialog(
                this,
                exception.getMessage(),
                "Trade-In Not Created",
                JOptionPane.ERROR_MESSAGE);
    }
}
private ServiceOrganization findServiceOrganization() {
    for (Organization organization
            : salesOrganization.getCompany().getOrganizations().getOrganizations()) {

        if (organization instanceof ServiceOrganization) {
            return (ServiceOrganization) organization;
        }
    }

    return null;
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
