/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas;

import Business.Ecosystem.Ecosystem;
import Business.Organization.LogisticsOrganization;
import Business.Organization.Organization;
import Business.Roles.LogisticsCoordinator;
import Business.User.User;
import Business.WorkTaskQueue.ProcessShipmentTask;
import Business.WorkTaskQueue.SendShipmentTask;
import Business.WorkTaskQueue.WorkTask;
import UserInterface.LogisticsCoordinator.ProcessShipmentJPanel;
import UserInterface.LogisticsCoordinator.SendShipmentJPanel;
import UserInterface.LogisticsCoordinator.WorkQueueJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ajay Alamuri
 */
public class LogisticsCoordinatorWorkAreaJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    LogisticsOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    
    /**
     * Creates new form LogisticsCoordinatorWorkAreaJPanel
     */
    public LogisticsCoordinatorWorkAreaJPanel(JPanel csp, User usr, Organization org, Ecosystem system) {
        this.organization = (LogisticsOrganization) org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        
        initComponents();
        lblTitle.setText(this.organization.getCompany().getName() + " - " + this.organization.getName());
        lblWelcome.setText("Welcome " + this.user.getEmployee().getPerson().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnCurrentTask = new javax.swing.JButton();
        btnQueue = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblWelcome.setText("Welcome <User>");
        add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 460, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Company Name> <Org Name>");
        lblTitle.setMaximumSize(new java.awt.Dimension(650, 600));
        lblTitle.setMinimumSize(new java.awt.Dimension(650, 600));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        btnCurrentTask.setText("Current Task");
        btnCurrentTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentTaskActionPerformed(evt);
            }
        });
        add(btnCurrentTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 160, 80));

        btnQueue.setText("Check Queue");
        btnQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueueActionPerformed(evt);
            }
        });
        add(btnQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 160, 80));

        jButton3.setText("jButton1");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 160, 80));

        jButton4.setText("jButton1");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 160, 80));

        jButton5.setText("jButton1");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 160, 80));

        jButton6.setText("jButton1");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 160, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void btnQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueueActionPerformed
        // TODO add your handling code here:
        WorkQueueJPanel wqjp = new WorkQueueJPanel(workArea, user, organization, business);
        this.workArea.add(wqjp, "OrgWorkQueue");
        ((CardLayout) this.workArea.getLayout()).next(workArea);
    }//GEN-LAST:event_btnQueueActionPerformed

    private void btnCurrentTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentTaskActionPerformed
        // TODO add your handling code here:
        WorkTask task = ((LogisticsCoordinator) user.getRole()).getCurrentTask();
        if (task == null) {
            JOptionPane.showMessageDialog(null, "You currently do not have a task assigned.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (task instanceof ProcessShipmentTask psTask) {
            ProcessShipmentJPanel psjp = new ProcessShipmentJPanel(workArea, user, organization, business, psTask);
            this.workArea.add(psjp, "ProcessShipment");
            ((CardLayout) this.workArea.getLayout()).next(workArea);
        } else if (task instanceof SendShipmentTask ssTask) {
            SendShipmentJPanel ssjp = new SendShipmentJPanel(workArea, user, organization, business, ssTask);
            this.workArea.add(ssjp, "SendShipment");
            ((CardLayout) this.workArea.getLayout()).next(workArea);
        }
    }//GEN-LAST:event_btnCurrentTaskActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCurrentTask;
    private javax.swing.JButton btnQueue;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
