/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas;

import Business.Ecosystem.Ecosystem;
import Business.Organization.Organization;
import Business.Organization.QualityAssuranceOrganization;
import Business.People.Employee;
import Business.People.Person;
import Business.Roles.QualityInspector;
import Business.User.User;
import Business.Vehicle.Part;
import Business.WorkTaskQueue.InspectCarBuildTask;
import Business.WorkTaskQueue.InspectPartTask;
import Business.WorkTaskQueue.WorkTask;
import UserInterface.QualityAssurance.InspectNewCarBuildJPanel;
import UserInterface.QualityAssurance.InspectPartJPanel;
import UserInterface.QualityAssurance.QADoneQueue;
import UserInterface.QualityAssurance.QAProfile;
import UserInterface.QualityAssurance.QARequestQueue;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ajay Alamuri
 * @author Meredith Molyneux
 */
public class QualityInspectorWorkAreaJPanel extends javax.swing.JPanel {
        QualityAssuranceOrganization organization;
        JPanel workArea;
        User user;
        Ecosystem business;
    /**
     * Creates new form QualityInspectorWorkAreaJPanel
     */
    public QualityInspectorWorkAreaJPanel(JPanel csp, User usr, Organization org, Ecosystem system) {
            this.organization = (QualityAssuranceOrganization)org;
            this.workArea = csp;
            this.user = usr;
            this.business = system;


        initComponents();
        lblTitle.setText(this.organization.getCompany().getName() + " - " + this.organization.getName());
        lblWelcome.setText("Welcome " + this.user.getEmployee().getPerson().getName());
        DemoData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMyRequest = new javax.swing.JButton();
        btnClosedRequests = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnQueue1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMyRequest.setText("My Requests");
        btnMyRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyRequestActionPerformed(evt);
            }
        });
        add(btnMyRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 160, 70));

        btnClosedRequests.setText("Actioned Requests");
        btnClosedRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClosedRequestsActionPerformed(evt);
            }
        });
        add(btnClosedRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 160, 70));

        btnMyProfile.setText("My Profile");
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileActionPerformed(evt);
            }
        });
        add(btnMyProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 160, 70));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblWelcome.setText("Welcome <User>");
        add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 460, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Company Name> <Org Name>");
        lblTitle.setMaximumSize(new java.awt.Dimension(650, 600));
        lblTitle.setMinimumSize(new java.awt.Dimension(650, 600));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, -1));

        btnQueue1.setText("Check Queue");
        btnQueue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueue1ActionPerformed(evt);
            }
        });
        add(btnQueue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 160, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMyRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyRequestActionPerformed
        WorkTask task = ((QualityInspector) user.getRole()).getCurrentTask();
        if (task == null) {
            JOptionPane.showMessageDialog(null, "You currently do not have a task assigned.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (task instanceof InspectPartTask ipTask) {
            InspectPartJPanel ipjp = new InspectPartJPanel(workArea, user, organization, business, ipTask);
            this.workArea.add(ipjp, "Inspect Part Panel");
            ((CardLayout) this.workArea.getLayout()).next(workArea);
        } else if (task instanceof InspectCarBuildTask icTask) {

            InspectNewCarBuildJPanel irjp = new InspectNewCarBuildJPanel(workArea, user, organization, business, icTask);
            this.workArea.add(irjp, "InspectNewCarBuild");
            ((CardLayout) this.workArea.getLayout()).next(workArea);
        }
    }//GEN-LAST:event_btnMyRequestActionPerformed

    private void btnClosedRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClosedRequestsActionPerformed
        QADoneQueue doneQueuePanel = new QADoneQueue(workArea, user, organization, business);
        workArea.add("QADoneQueuePanel", doneQueuePanel);

        // FORCE THE INSTANCE TO RE-READ THE SHARED ARRAY DATA BEFORE DISPLAY
        doneQueuePanel.refreshCompletedTable();

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnClosedRequestsActionPerformed

    private void btnMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileActionPerformed
        QAProfile pmp = new QAProfile(workArea, user, organization, business);
        this.workArea.add(pmp, "ProdMgrWorkQueue");
        ((CardLayout) this.workArea.getLayout()).next(workArea);
    }//GEN-LAST:event_btnMyProfileActionPerformed

    private void btnQueue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueue1ActionPerformed
        QARequestQueue activeQueuePanel = new QARequestQueue(workArea, user, organization, business);

        workArea.add("QARequestQueuePanel", activeQueuePanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnQueue1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClosedRequests;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnMyRequest;
    private javax.swing.JButton btnQueue1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
  
    private void DemoData() {
    try {
        // Sample vehicle datasets to generate diverse and distinct test data row items
        String[] makes = {"Ford", "Tesla", "Toyota", "BMW", "Chevrolet", "Honda", "Audi", "Nissan", "Rivian", "Porsche"};
        String[] models = {"Mustang", "Model 3", "Camry", "M3", "Silverado", "Civic", "A4", "Altima", "R1T", "911"};

        for (int i = 0; i < 10; i++) {
            // 1. Structural infrastructure data creation
            Person p = new Person("Inspector " + i);
            Employee emp = organization.getEmployees().createEmployee(p);
            User newUser = organization.getUsers().createUser(emp, "QA" + i, "temp", new QualityInspector());

            // 2. Component Inspection Task Generation
            Part part = new Part(i);
            organization.getInTasks().createInspectPartTask(newUser, part);

            // 3. Vehicle Build Inspection Task Generation
            // Picks values sequentially out of our dataset arrays to match the current loop index
            String mockMake = makes[i % makes.length];
            String mockModel = models[i % models.length];

            // Fires the factory instantiation request into your shared WorkQueue database
            organization.getInTasks().createInspectCarBuildTask(newUser, mockMake, mockModel);
        }

    } catch (Exception e) {
        // Logs framework generation failures cleanly out to your NetBeans Output window pane
        System.err.println("Error initializing system QA demonstration data: " + e.getMessage());
    }
}


}
