/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas;

import Business.Ecosystem.Ecosystem;
import Business.Organization.Organization;
import Business.User.User;
import javax.swing.JPanel;
import Business.Roles.ServiceTechnician;
import Business.WorkTaskQueue.ServiceAppointmentTask;
import Business.WorkTaskQueue.WorkTask;
import Business.WorkTaskQueue.TradeInTask;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Ajay Alamuri
 * @author Nicholas Woodward
 */
public class ServiceManagerWorkAreaJPanel extends javax.swing.JPanel {
    // Service Center organization receiving customer-service appointments.
    private Organization serviceOrganization;

    // Signed-in manager, used when coordinating appointments.
    private User serviceManager;

    // Table showing appointments awaiting technician assignment.
    private DefaultTableModel tableModel;
    private JTable appointmentsTable;
    // Rotates assignment across available technicians.
    private int nextTechnicianIndex = 0;
    /**
     * Creates new form ServiceManagerWorkAreaJPanel
     */
    public ServiceManagerWorkAreaJPanel(JPanel csp, User usr, Organization org, Ecosystem system) {
        initComponents();
        this.serviceOrganization = org;
        this.serviceManager = usr;
        buildServiceManagerScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
/**
 * Builds the Service Center manager dashboard for incoming appointments.
 */
private void buildServiceManagerScreen() {
    removeAll();
    setLayout(new BorderLayout());

    JPanel headerPanel = new JPanel(new BorderLayout());
    headerPanel.setBackground(new Color(45, 84, 105));
    headerPanel.setBorder(new EmptyBorder(16, 20, 16, 20));

    JLabel titleLabel = new JLabel(
        serviceOrganization.getCompany().getName()
        + " - "
        + serviceOrganization.getName());
    titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 22));
    titleLabel.setForeground(Color.WHITE);
    titleLabel.setHorizontalAlignment(SwingConstants.CENTER);

    JLabel subtitleLabel = new JLabel(
        "Welcome "
        + serviceManager.getEmployee().getPerson().getName()
        + " | Review appointments and assign available technicians");
    subtitleLabel.setForeground(new Color(220, 235, 245));
    subtitleLabel.setHorizontalAlignment(SwingConstants.CENTER);

    headerPanel.add(titleLabel, BorderLayout.NORTH);
    headerPanel.add(subtitleLabel, BorderLayout.SOUTH);

    tableModel = new DefaultTableModel(
            new Object[]{"Task ID", "Request Type", "Vehicle VIN",
                "Requested By", "Assigned Technician", "Status"}, 0) {        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    appointmentsTable = new JTable(tableModel);
    appointmentsTable.setRowHeight(26);

    JLabel instructionsLabel = new JLabel(
            "Select an appointment, then assign it to the available technician.");
    instructionsLabel.setBorder(new EmptyBorder(10, 12, 10, 12));

    JPanel centerPanel = new JPanel(new BorderLayout(0, 8));
    centerPanel.setBorder(new EmptyBorder(10, 16, 10, 16));
    centerPanel.add(instructionsLabel, BorderLayout.NORTH);
    centerPanel.add(new JScrollPane(appointmentsTable), BorderLayout.CENTER);

    JButton assignButton = new JButton("Assign Selected Appointment");
    assignButton.addActionListener(event -> assignSelectedAppointment());

    JButton completeTradeInButton = new JButton(
        "Complete Selected Trade-In");
completeTradeInButton.addActionListener(
        event -> completeSelectedTradeIn());

JPanel buttonPanel = new JPanel();
buttonPanel.add(assignButton);
buttonPanel.add(completeTradeInButton);

    add(headerPanel, BorderLayout.NORTH);
    add(centerPanel, BorderLayout.CENTER);
    add(buttonPanel, BorderLayout.SOUTH);

    populateAppointments();
    revalidate();
    repaint();
}

/**
 * Loads incoming appointments and trade-in evaluations into the manager table.
 */
private void populateAppointments() {
    tableModel.setRowCount(0);

    for (WorkTask workTask : serviceOrganization.getInTasks().getTasks()) {
        String requestType;
        int vin;

        if (workTask instanceof ServiceAppointmentTask) {
            requestType = "Service Appointment";
            vin = ((ServiceAppointmentTask) workTask).getVIN();

        } else if (workTask instanceof TradeInTask) {
            requestType = "Trade-In Evaluation";
            vin = ((TradeInTask) workTask).getVIN();

        } else {
            continue;
        }

        String technicianName = workTask.getAssignee() == null
                ? "Unassigned"
                : workTask.getAssignee().toString();

        String status = workTask.isCompleted()
                ? "Completed"
                : workTask.getAssignee() == null
                        ? "Awaiting Assignment"
                        : "Assigned";

        tableModel.addRow(new Object[]{
            workTask.getID(),
            requestType,
            vin,
            workTask.getAssigner(),
            technicianName,
            status
        });
    }
}

/**
 * Assigns the selected appointment to the dealership service technician.
 */
private void assignSelectedAppointment() {
    int selectedRow = appointmentsTable.getSelectedRow();
    if (selectedRow >= 0
            && "Trade-In Evaluation".equals(
                    tableModel.getValueAt(selectedRow, 1))) {
        JOptionPane.showMessageDialog(
                this,
                "Trade-in evaluations are completed by the Service Manager.",
                "Select a Service Appointment",
                JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(
                this,
                "Select a service appointment first.",
                "No Appointment Selected",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int taskId = (Integer) tableModel.getValueAt(selectedRow, 0);
    User technician = findAvailableServiceTechnician();

    if (technician == null) {
        JOptionPane.showMessageDialog(
                this,
                "No Service Technician is currently available.",
                "Technician Unavailable",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    for (WorkTask workTask : serviceOrganization.getInTasks().getTasks()) {
        if (workTask.getID() == taskId
                && workTask instanceof ServiceAppointmentTask) {

            if (workTask.getAssignee() != null) {
                JOptionPane.showMessageDialog(
                        this,
                        "This appointment is already assigned.",
                        "Appointment Assigned",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            workTask.setAssignee(technician);
            populateAppointments();

            JOptionPane.showMessageDialog(
                    this,
                    "Appointment assigned to " + technician + ".");
            return;
        }
    }
}
/**
 * Completes the trade-in evaluation selected by the Service Manager.
 */
private void completeSelectedTradeIn() {
    int selectedRow = appointmentsTable.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(
                this,
                "Select a trade-in evaluation first.",
                "No Request Selected",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (!"Trade-In Evaluation".equals(
            tableModel.getValueAt(selectedRow, 1))) {
        JOptionPane.showMessageDialog(
                this,
                "Select a Trade-In Evaluation row.",
                "Incorrect Request Type",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int taskId = (Integer) tableModel.getValueAt(selectedRow, 0);

    for (WorkTask workTask : serviceOrganization.getInTasks().getTasks()) {
        if (workTask.getID() == taskId
                && workTask instanceof TradeInTask) {

            workTask.Complete();
            serviceOrganization.getInTasks().popTask(workTask);
            serviceOrganization.getOutTasks().pushTask(workTask);

            populateAppointments();

            JOptionPane.showMessageDialog(
                    this,
                    "Trade-in evaluation completed successfully.");
            return;
        }
    }
}
/**
 * Selects an available technician using round-robin assignment.
 *
 * @return an available technician, or null when every technician is busy
 */
private User findAvailableServiceTechnician() {
    java.util.ArrayList<User> technicians = new java.util.ArrayList<>();

    for (User user : serviceOrganization.getUsers().getUsers()) {
        if (user.getRole() instanceof ServiceTechnician) {
            technicians.add(user);
        }
    }

    if (technicians.isEmpty()) {
        return null;
    }

    int startingIndex = nextTechnicianIndex % technicians.size();

    for (int offset = 0; offset < technicians.size(); offset++) {
        int technicianIndex =
                (startingIndex + offset) % technicians.size();
        User technician = technicians.get(technicianIndex);

        if (!isTechnicianBusy(technician)) {
            nextTechnicianIndex =
                    (technicianIndex + 1) % technicians.size();
            return technician;
        }
    }

    return null;
}
/**
 * Checks whether a technician owns an incomplete service appointment.
 *
 * @param technician technician whose workload is being checked
 * @return true when the technician already has active work
 */
private boolean isTechnicianBusy(User technician) {
    for (WorkTask workTask
            : serviceOrganization.getInTasks().getTasks()) {

        if (workTask instanceof ServiceAppointmentTask
                && !workTask.isCompleted()
                && workTask.getAssignee() == technician) {
            return true;
        }
    }

    return false;
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
