/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas;

import Business.Ecosystem.Ecosystem;
import Business.Organization.Organization;
import Business.User.User;
import javax.swing.JPanel;
import Business.WorkTaskQueue.ServiceAppointmentTask;
import Business.WorkTaskQueue.WorkTask;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ajay Alamuri
 * @author nicholaswoodward
 */
public class ServiceTechnicianWorkAreaJPanel extends javax.swing.JPanel {
    // Dealership Service Center organization containing assigned appointments.
    private Organization serviceOrganization;

    // Signed-in technician who completes assigned service work.
    private User serviceTechnician;

    // Table showing this technician's assigned service appointments.
    private DefaultTableModel tableModel;
    private JTable appointmentsTable;
    /**
     * Creates new form ServiceTechnicianWorkAreaJPanel
     */
    public ServiceTechnicianWorkAreaJPanel(JPanel csp, User usr, Organization org, Ecosystem system) {
        initComponents();
        this.serviceOrganization = org;
        this.serviceTechnician = usr;
        buildTechnicianScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
 * Builds the Service Technician work area for completing assigned appointments.
 */
private void buildTechnicianScreen() {
    removeAll();
    setLayout(new BorderLayout());

    JPanel headerPanel = new JPanel(new BorderLayout());
    headerPanel.setBackground(new Color(112, 72, 45));
    headerPanel.setBorder(new EmptyBorder(16, 20, 16, 20));

    JLabel titleLabel = new JLabel("Service Technician Work Queue");
    titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 22));
    titleLabel.setForeground(Color.WHITE);
    titleLabel.setHorizontalAlignment(SwingConstants.CENTER);

    JLabel subtitleLabel = new JLabel(
            "Complete dealership service appointments assigned by the Service Manager.");
    subtitleLabel.setForeground(new Color(245, 230, 215));
    subtitleLabel.setHorizontalAlignment(SwingConstants.CENTER);

    headerPanel.add(titleLabel, BorderLayout.NORTH);
    headerPanel.add(subtitleLabel, BorderLayout.SOUTH);

    tableModel = new DefaultTableModel(
            new Object[]{"Task ID", "Vehicle VIN", "Requested By", "Status"}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    appointmentsTable = new JTable(tableModel);
    appointmentsTable.setRowHeight(26);

    JLabel instructionsLabel = new JLabel(
            "Select an assigned appointment when its service work is complete.");
    instructionsLabel.setBorder(new EmptyBorder(10, 12, 10, 12));

    JPanel centerPanel = new JPanel(new BorderLayout(0, 8));
    centerPanel.setBorder(new EmptyBorder(10, 16, 10, 16));
    centerPanel.add(instructionsLabel, BorderLayout.NORTH);
    centerPanel.add(new JScrollPane(appointmentsTable), BorderLayout.CENTER);

    JButton completeButton = new JButton("Complete Selected Service");
    completeButton.addActionListener(event -> completeSelectedAppointment());

    JPanel buttonPanel = new JPanel();
    buttonPanel.add(completeButton);

    add(headerPanel, BorderLayout.NORTH);
    add(centerPanel, BorderLayout.CENTER);
    add(buttonPanel, BorderLayout.SOUTH);

    populateAssignedAppointments();
    revalidate();
    repaint();
}

/**
 * Displays only appointments assigned to the signed-in technician.
 */
private void populateAssignedAppointments() {
    tableModel.setRowCount(0);

    for (WorkTask workTask : serviceOrganization.getInTasks().getTasks()) {
        if (workTask instanceof ServiceAppointmentTask
                && workTask.getAssignee() == serviceTechnician) {

            ServiceAppointmentTask appointment
                    = (ServiceAppointmentTask) workTask;

            String status = appointment.isCompleted()
                    ? "Completed"
                    : "Ready for Service";

            tableModel.addRow(new Object[]{
                appointment.getID(),
                appointment.getVIN(),
                appointment.getAssigner(),
                status
            });
        }
    }
}

/**
 * Marks the selected assigned appointment as completed.
 */
private void completeSelectedAppointment() {
    int selectedRow = appointmentsTable.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(
                this,
                "Select a service appointment first.",
                "No Appointment Selected",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int taskId = (Integer) tableModel.getValueAt(selectedRow, 0);

    for (WorkTask workTask : serviceOrganization.getInTasks().getTasks()) {
        if (workTask.getID() == taskId
                && workTask instanceof ServiceAppointmentTask
                && workTask.getAssignee() == serviceTechnician) {

            if (workTask.isCompleted()) {
                JOptionPane.showMessageDialog(
                        this,
                        "This appointment has already been completed.",
                        "Service Complete",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            workTask.Complete();
            populateAssignedAppointments();

            JOptionPane.showMessageDialog(
                    this,
                    "Service appointment completed successfully.");
            return;
        }
    }
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
