/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas;

import Business.Ecosystem.Ecosystem;
import Business.Organization.Organization;
import Business.User.User;
import javax.swing.JPanel;
import Business.Roles.ServiceTechnician;
import Business.WorkTaskQueue.ServiceAppointmentTask;
import Business.WorkTaskQueue.WorkTask;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Ajay Alamuri
 * @author Nicholas Woodward
 */
public class ServiceManagerWorkAreaJPanel extends javax.swing.JPanel {
    // Service Center organization receiving customer-service appointments.
    private Organization serviceOrganization;

    // Signed-in manager, used when coordinating appointments.
    private User serviceManager;

    // Table showing appointments awaiting technician assignment.
    private DefaultTableModel tableModel;
    private JTable appointmentsTable;
    /**
     * Creates new form ServiceManagerWorkAreaJPanel
     */
    public ServiceManagerWorkAreaJPanel(JPanel csp, User usr, Organization org, Ecosystem system) {
        initComponents();
        this.serviceOrganization = org;
        this.serviceManager = usr;
        buildServiceManagerScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
/**
 * Builds the Service Center manager dashboard for incoming appointments.
 */
private void buildServiceManagerScreen() {
    removeAll();
    setLayout(new BorderLayout());

    JPanel headerPanel = new JPanel(new BorderLayout());
    headerPanel.setBackground(new Color(45, 84, 105));
    headerPanel.setBorder(new EmptyBorder(16, 20, 16, 20));

    JLabel titleLabel = new JLabel("Dealership Service Center");
    titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 22));
    titleLabel.setForeground(Color.WHITE);
    titleLabel.setHorizontalAlignment(SwingConstants.CENTER);

    JLabel subtitleLabel = new JLabel(
            "Review customer appointments and assign them to a service technician.");
    subtitleLabel.setForeground(new Color(220, 235, 245));
    subtitleLabel.setHorizontalAlignment(SwingConstants.CENTER);

    headerPanel.add(titleLabel, BorderLayout.NORTH);
    headerPanel.add(subtitleLabel, BorderLayout.SOUTH);

    tableModel = new DefaultTableModel(
            new Object[]{"Task ID", "Vehicle VIN", "Requested By",
                "Assigned Technician", "Status"}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    appointmentsTable = new JTable(tableModel);
    appointmentsTable.setRowHeight(26);

    JLabel instructionsLabel = new JLabel(
            "Select an appointment, then assign it to the available technician.");
    instructionsLabel.setBorder(new EmptyBorder(10, 12, 10, 12));

    JPanel centerPanel = new JPanel(new BorderLayout(0, 8));
    centerPanel.setBorder(new EmptyBorder(10, 16, 10, 16));
    centerPanel.add(instructionsLabel, BorderLayout.NORTH);
    centerPanel.add(new JScrollPane(appointmentsTable), BorderLayout.CENTER);

    JButton assignButton = new JButton("Assign Selected Appointment");
    assignButton.addActionListener(event -> assignSelectedAppointment());

    JPanel buttonPanel = new JPanel();
    buttonPanel.add(assignButton);

    add(headerPanel, BorderLayout.NORTH);
    add(centerPanel, BorderLayout.CENTER);
    add(buttonPanel, BorderLayout.SOUTH);

    populateAppointments();
    revalidate();
    repaint();
}

/**
 * Loads incoming service appointments into the manager table.
 */
private void populateAppointments() {
    tableModel.setRowCount(0);

    for (WorkTask workTask : serviceOrganization.getInTasks().getTasks()) {
        if (workTask instanceof ServiceAppointmentTask) {
            ServiceAppointmentTask appointment
                    = (ServiceAppointmentTask) workTask;

            String technicianName = appointment.getAssignee() == null
                    ? "Unassigned"
                    : appointment.getAssignee().toString();

            String status = appointment.isCompleted()
                    ? "Completed"
                    : appointment.getAssignee() == null
                            ? "Awaiting Assignment"
                            : "Assigned";

            tableModel.addRow(new Object[]{
                appointment.getID(),
                appointment.getVIN(),
                appointment.getAssigner(),
                technicianName,
                status
            });
        }
    }
}

/**
 * Assigns the selected appointment to the dealership service technician.
 */
private void assignSelectedAppointment() {
    int selectedRow = appointmentsTable.getSelectedRow();

    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(
                this,
                "Select a service appointment first.",
                "No Appointment Selected",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int taskId = (Integer) tableModel.getValueAt(selectedRow, 0);
    User technician = findServiceTechnician();

    if (technician == null) {
        JOptionPane.showMessageDialog(
                this,
                "No Service Technician account is available.",
                "Technician Unavailable",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    for (WorkTask workTask : serviceOrganization.getInTasks().getTasks()) {
        if (workTask.getID() == taskId
                && workTask instanceof ServiceAppointmentTask) {

            if (workTask.getAssignee() != null) {
                JOptionPane.showMessageDialog(
                        this,
                        "This appointment is already assigned.",
                        "Appointment Assigned",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            workTask.setAssignee(technician);
            populateAppointments();

            JOptionPane.showMessageDialog(
                    this,
                    "Appointment assigned to " + technician + ".");
            return;
        }
    }
}

/**
 * Finds the technician user within this Service Center.
 *
 * @return technician user, or null when one is not available
 */
private User findServiceTechnician() {
    for (User user : serviceOrganization.getUsers().getUsers()) {
        if (user.getRole() instanceof ServiceTechnician) {
            return user;
        }
    }

    return null;
}    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
