/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WarehouseClerk;

import Business.Ecosystem.Ecosystem;
import Business.Ecosystem.Network;
import Business.Enterprise.EnterpriseDirectory;
import Business.Enterprise.ManufacturerEnterprise;
import Business.Organization.Organization;
import Business.Organization.ProductionOrganization;
import Business.Organization.WarehousingOrganization;
import Business.User.User;
import Business.WorkTaskQueue.GetPartTask;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ajay Alamuri
 */
public class BackOrderJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    WarehousingOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    GetPartTask task;
    
    /**
     * Creates new form BackOrderJPanel
     */
    public BackOrderJPanel(JPanel csp, User usr, WarehousingOrganization org, Ecosystem system, GetPartTask tsk) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        this.task = tsk;
        
        initComponents();
        lblTitle.setText(organization.getName() + " Back Order Manufacturers");
        
        refreshManufacturers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblManufacturers = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnBackOrder = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblManufacturers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Manufacturers"
            }
        ));
        jScrollPane1.setViewportView(tblManufacturers);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 610, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name>  Back Order Manufacturers");
        lblTitle.setMaximumSize(new java.awt.Dimension(650, 600));
        lblTitle.setMinimumSize(new java.awt.Dimension(650, 600));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 130, -1));

        btnBackOrder.setText("Request Back Order");
        btnBackOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackOrderActionPerformed(evt);
            }
        });
        add(btnBackOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to previous page
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBackOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackOrderActionPerformed
        // Dispatch part order task + set back ordered state for current task
        
        if (task.isCompleted()) {
            JOptionPane.showMessageDialog(null, "Task is already completed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int selectedRow = tblManufacturers.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblManufacturers.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select a manufacturer from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ManufacturerEnterprise selectedMfe = (ManufacturerEnterprise) tblManufacturers.getValueAt(selectedRow, 0);
        if (selectedMfe == null) {
            JOptionPane.showMessageDialog(null, "Failed to back order from selected manufacturer.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (task.isBackordered()) {
            JOptionPane.showMessageDialog(null, "Backorder already requested for this task.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        for (Organization o : selectedMfe.getOrganizations().getOrganizations()) {
            if (o instanceof ProductionOrganization po) {
                if (task.BackOrder(po)) JOptionPane.showMessageDialog(null, "Backorder successfully requested!", "Warning", JOptionPane.WARNING_MESSAGE);
                else JOptionPane.showMessageDialog(null, "Failed to requrest backorder", "Warning", JOptionPane.WARNING_MESSAGE);
                break;
            }
        }
        
        workArea.remove(this);
        
        Component[] panelStack = workArea.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];
        GetPartJPanel gpjp = (GetPartJPanel) lastPanel;
        gpjp.refreshFields(); // Update buttons
        
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBackOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblManufacturers;
    // End of variables declaration//GEN-END:variables
    
    private void refreshManufacturers() {
        DefaultTableModel model = (DefaultTableModel) tblManufacturers.getModel();
        
        model.setRowCount(0);
        
        for (Network net : business.getNetworks()) {
            EnterpriseDirectory ed = net.getEnterprises();
            if (ed.findEnterprise(organization.getCompany().getID()) != null) {
                for (ManufacturerEnterprise me : ed.getManufacturers()) {
                    Object[] row = new Object[1];
                    
                    row[0] = me;
                    
                    model.addRow(row);
                }
            }
        }
    }
}
