/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WarehouseClerk;

import Business.Ecosystem.Ecosystem;
import Business.Enterprise.SupplierEnterprise;
import Business.Organization.WarehousingOrganization;
import Business.Roles.WarehouseClerk;
import Business.User.User;
import Business.Vehicle.Part;
import Business.WorkTaskQueue.GetPartTask;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ajay Alamuri
 */
public class GetPartJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    WarehousingOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    GetPartTask task;
    
    /**
     * Creates new form ProcessShipmentJPanel
     */
    public GetPartJPanel(JPanel csp, User usr, WarehousingOrganization org, Ecosystem system, GetPartTask tsk) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        this.task = tsk;
        
        initComponents();
        lblTitle.setText(organization.getName() + " Incoming Shipment Processing");
        
        refreshFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPart = new javax.swing.JLabel();
        txtPart = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnComplete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnBackOrder = new javax.swing.JButton();
        btnUnassign = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 153));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setPreferredSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Get Part");
        lblTitle.setMaximumSize(new java.awt.Dimension(650, 600));
        lblTitle.setMinimumSize(new java.awt.Dimension(650, 600));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        lblPart.setText("Part:");
        add(lblPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 40, -1));

        txtPart.setEditable(false);
        add(txtPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 160, -1));

        lblStock.setText("Current Stock:");
        add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 90, -1));

        txtStock.setEditable(false);
        add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 160, -1));

        lblQuantity.setText("Requested Quantity:");
        add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 120, -1));

        txtQuantity.setEditable(false);
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 160, -1));

        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });
        add(btnComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 90, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 130, -1));

        btnBackOrder.setText("Back Order");
        btnBackOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackOrderActionPerformed(evt);
            }
        });
        add(btnBackOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 90, -1));

        btnUnassign.setText("Unassign");
        btnUnassign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnassignActionPerformed(evt);
            }
        });
        add(btnUnassign, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to previous page
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // Add new stock to company database
        
        // Validate if task still needs to be complete
        if (task.isCompleted()) {
            JOptionPane.showMessageDialog(null, "Task has already been completed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Field validation
        String strQuantity = txtQuantity.getText();
        if (strQuantity.isBlank()) {
            JOptionPane.showMessageDialog(null, "Requested quantity cannot be blank.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int quantity = -1;
        try {
            quantity = Integer.parseInt(strQuantity);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Requested quantity must be an integer.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Update in backend
        SupplierEnterprise company = (SupplierEnterprise) organization.getCompany();
        Part part = task.getPart();
        int oldQuantity = company.getPartQuantity(part);
        company.setPartQuantity(part, oldQuantity - quantity);
        
        // Update task status
        organization.getInTasks().popTask(task);
        organization.getOutTasks().pushTask(task);
        ((WarehouseClerk) user.getRole()).completeTask();
        
        // Notify and refresh
        JOptionPane.showMessageDialog(null, "Part successfully removed from stock, please return and track a new task.", "Success", JOptionPane.INFORMATION_MESSAGE);
        refreshFields();
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void btnBackOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackOrderActionPerformed
        // Create build order for specified part
        
        // Validate if task still needs to be complete
        if (task.isCompleted()) {
            JOptionPane.showMessageDialog(null, "Task has already been completed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        BackOrderJPanel bojp = new BackOrderJPanel(workArea, user, organization, business, task);
        this.workArea.add(bojp, "BackOrders");
        ((CardLayout) this.workArea.getLayout()).next(workArea);
    }//GEN-LAST:event_btnBackOrderActionPerformed

    private void btnUnassignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnassignActionPerformed
        // Unassign task
        
        if (task.getAssignee() != null) {
            
            // Display confirmation dialog
            int dialogResult = JOptionPane.showConfirmDialog(null,"Are you sure you want to unassign this task?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                task.setAssignee(null);
                ((WarehouseClerk) user.getRole()).setCurrentTask(null);
                
                workArea.remove(this);
                ((CardLayout) workArea.getLayout()).previous(workArea);
            }
        }
    }//GEN-LAST:event_btnUnassignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBackOrder;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnUnassign;
    private javax.swing.JLabel lblPart;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtPart;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

    public void refreshFields() {
        int stock = ((SupplierEnterprise) organization.getCompany()).getPartQuantity(task.getPart());
        int quantity = task.getQuantity();
        
        txtPart.setText(task.getPart().toString());
        txtStock.setText(String.valueOf(stock));
        txtQuantity.setText(String.valueOf(quantity));
        
        if (quantity > stock) btnComplete.setEnabled(false);
        else btnComplete.setEnabled(true);
        
        if (task.isBackordered()) btnBackOrder.setEnabled(false);
        else btnBackOrder.setEnabled(true);
    }
}
