/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WarehouseClerk;

import UserInterface.LogisticsCoordinator.*;
import Business.Ecosystem.Ecosystem;
import Business.Enterprise.SupplierEnterprise;
import Business.Organization.LogisticsOrganization;
import Business.Roles.LogisticsCoordinator;
import Business.User.User;
import Business.Vehicle.Part;
import Business.WorkTaskQueue.SendShipmentTask;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ajay Alamuri
 */
public class SendShipmentJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    LogisticsOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    SendShipmentTask task;
    
    /**
     * Creates new form SendShipmentJPanel
     */
    public SendShipmentJPanel(JPanel csp, User usr, LogisticsOrganization org, Ecosystem system, SendShipmentTask tsk) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        this.task = tsk;
        
        initComponents();
        lblTitle.setText(organization.getName() + " Outbound Shipment Processing");
        
        refreshFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPart = new javax.swing.JLabel();
        txtPart = new javax.swing.JTextField();
        lblOrderQuantity = new javax.swing.JLabel();
        txtOrderQuantity = new javax.swing.JTextField();
        lblDealership = new javax.swing.JLabel();
        txtDealership = new javax.swing.JTextField();
        btnComplete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        btnDefer = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 153));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Outbound Shipment Processing");
        lblTitle.setMaximumSize(new java.awt.Dimension(650, 600));
        lblTitle.setMinimumSize(new java.awt.Dimension(650, 600));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        lblPart.setText("Part:");
        add(lblPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 40, -1));

        txtPart.setEditable(false);
        add(txtPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 160, -1));

        lblOrderQuantity.setText("Requested Quantity:");
        add(lblOrderQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 120, -1));

        txtOrderQuantity.setEditable(false);
        add(txtOrderQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 160, -1));

        lblDealership.setText("Requesting Dealership:");
        add(lblDealership, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 130, -1));

        txtDealership.setEditable(false);
        add(txtDealership, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 160, -1));

        btnComplete.setText("Complete");
        btnComplete.setEnabled(false);
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });
        add(btnComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 90, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 130, -1));

        lblStock.setText("Current Stock:");
        add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 90, -1));

        txtStock.setEditable(false);
        add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 160, -1));

        btnDefer.setText("Defer Shipment");
        btnDefer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeferActionPerformed(evt);
            }
        });
        add(btnDefer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // Add new stock to company database

        // Validate if task still needs to be complete
        if (task.isCompleted()) {
            JOptionPane.showMessageDialog(null, "Task has already been completed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Update in backend
        SupplierEnterprise company = (SupplierEnterprise) organization.getCompany();
        Part part = task.getPart();
        int oldQuantity = company.getPartQuantity(part);
        company.setPartQuantity(part, oldQuantity - task.getPartCount());

        // Update task status ===============================WIP===============================
        
        /*
        * Remove task from inQueue
        * Update stock for target dealership
        */
        
        
        organization.getInTasks().popTask(task);
        organization.getOutTasks().pushTask(task);
        ((LogisticsCoordinator) user.getRole()).completeTask();

        // Notify and refresh
        JOptionPane.showMessageDialog(null, "Shipment successfully sent, please return and track a new task.", "Success", JOptionPane.INFORMATION_MESSAGE);
        refreshFields();
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to previous page
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeferActionPerformed
        // Unassign task and return to previous page
        
        if (task.getAssignee() != null) {
            
            // Display confirmation dialog for deferral
            int dialogResult = JOptionPane.showConfirmDialog(null,"Are you sure you want to defer this shipment?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                task.setAssignee(null);
                ((LogisticsCoordinator) user.getRole()).setCurrentTask(null);
                
                workArea.remove(this);
                ((CardLayout) workArea.getLayout()).previous(workArea);
            }
        }
    }//GEN-LAST:event_btnDeferActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnDefer;
    private javax.swing.JLabel lblDealership;
    private javax.swing.JLabel lblOrderQuantity;
    private javax.swing.JLabel lblPart;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDealership;
    private javax.swing.JTextField txtOrderQuantity;
    private javax.swing.JTextField txtPart;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

    private void refreshFields() {
        int required = task.getPartCount();
        int stock = ((SupplierEnterprise) organization.getCompany()).getPartQuantity(task.getPart());
        
        txtDealership.setText(task.getDealership().toString());
        txtPart.setText(task.getPart().toString());
        txtOrderQuantity.setText(String.valueOf(required));
        txtStock.setText(String.valueOf(stock));
        
        if (stock >= required) btnComplete.setEnabled(true);
        else btnComplete.setEnabled(false);
    }
}
