/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WarehouseClerk;

import Business.Ecosystem.Ecosystem;
import Business.Organization.WarehousingOrganization;
import Business.Roles.WarehouseClerk;
import Business.User.User;
import Business.WorkTaskQueue.GetPartTask;
import Business.WorkTaskQueue.WorkTask;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ajay Alamuri
 */
public class WorkQueueJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    WarehousingOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    
    /**
     * Creates new form WorkQueue
     */
    public WorkQueueJPanel(JPanel csp, User usr, WarehousingOrganization org, Ecosystem system) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        
        initComponents();
        lblTitle.setText(this.organization.getName() + " Queue");
        
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTasks = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 153));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setPreferredSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Queue");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 130, -1));

        tblTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Task", "Assigned By", "Assigned To", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblTasks);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 610, 220));

        btnAssign.setText("Assign To Me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to previous page
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // Assign user to handle task and task as user's current task
        
        // Selection validation
        int selectedRow = tblTasks.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblTasks.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select a task from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        WorkTask selectedTask = (WorkTask) tblTasks.getValueAt(selectedRow, 0);
        if (selectedTask.getAssignee() != null) {
            JOptionPane.showMessageDialog(null, "An employee is already working on this task, please select another task.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (((WarehouseClerk) user.getRole()).getCurrentTask() != null) {
            JOptionPane.showMessageDialog(null, "Cannot select another task while currently assigned one.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ((WarehouseClerk) user.getRole()).setCurrentTask(selectedTask);
        selectedTask.setAssignee(user);
        
        // Notify + refresh
        JOptionPane.showMessageDialog(null, "Successfully assigned task!", "Success", JOptionPane.INFORMATION_MESSAGE);
        refreshTable();
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblTasks;
    // End of variables declaration//GEN-END:variables

    public void refreshTable() {
        // Fill table with necessary data
        DefaultTableModel model = (DefaultTableModel) tblTasks.getModel();
        
        model.setRowCount(0);
        
        for (WorkTask task : this.organization.getInTasks().getTasks()) {
            Object[] row = new Object[4];
            
            row[0] = task;
            row[1] = task.getAssigner();
            row[2] = task.getAssignee() == null ? null : task.getAssignee();
            row[3] = ((GetPartTask) task).isBackordered() ? "Backordered" : task.getAssignee() == null ? "Waiting" : "In Progress";
            
            model.addRow(row);
        }
    }
}
