/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import Business.Ecosystem.Ecosystem;
import Business.Organization.AdminOrganization;
import Business.Organization.LogisticsOrganization;
import Business.Organization.Organization;
import Business.Organization.ProductionOrganization;
import Business.Organization.QualityAssuranceOrganization;
import Business.Organization.SalesOrganization;
import Business.Organization.ServiceOrganization;
import Business.Organization.WarehousingOrganization;
import Business.People.Employee;
import Business.Roles.Admin;
import Business.Roles.CustomerServiceRepresentative;
import Business.Roles.LogisticsCoordinator;
import Business.Roles.ProductionManager;
import Business.Roles.QualityInspector;
import Business.Roles.Role;
import Business.Roles.SalesRepresentative;
import Business.Roles.ServiceManager;
import Business.Roles.ServiceTechnician;
import Business.Roles.WarehouseClerk;
import Business.User.User;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ajay Alamuri
 */
public class CreateUsersJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    AdminOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    Organization selectedOrganization;
    Employee selectedEmployee;
    
    /**
     * Creates new form CreateUsersJPanel
     */
    public CreateUsersJPanel(JPanel csp, User usr, AdminOrganization org, Ecosystem system) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        
        initComponents();
        lblTitle.setText(this.organization.getCompany().getName() + " Create User");
        
        refreshOrganizations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganizations = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        txtUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Company Name> Create User");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        tblOrganizations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Organization"
            }
        ));
        tblOrganizations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrganizationsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrganizations);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 420));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 130, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 160, -1));

        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 70, -1));

        btnCreate.setText("Create User");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 140, -1));

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Employee"
            }
        ));
        tblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmployees);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 420, 170));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 160, -1));

        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 70, -1));

        lblRole.setText("Role:");
        add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 40, 20));

        cmbRole.setMaximumRowCount(2);
        cmbRole.setEnabled(false);
        add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        // Validate organization, employee, username, password, role
        if (selectedOrganization == null) {
            JOptionPane.showMessageDialog(null, "Please select an organization from the left table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (selectedEmployee == null) {
            JOptionPane.showMessageDialog(null, "Please select an employee from the top table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int selectedIndex = cmbRole.getSelectedIndex();
        if (selectedIndex < 0 || selectedIndex > cmbRole.getItemCount()) {
            JOptionPane.showMessageDialog(null, "Please select a valid role from the combo box first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String roleName = cmbRole.getItemAt(selectedIndex);
        if (roleName.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please select a valid role from the combo box first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Role role;
        switch (roleName) {
            case "Admin" -> role = new Admin();
            case "Logistics Coordinator" -> role = new LogisticsCoordinator();
            case "Warehouse Clerk" -> role = new WarehouseClerk();
            case "Sales Representative" -> role = new SalesRepresentative();
            case "Customer Service Representative" -> role = new CustomerServiceRepresentative();
            case "Service Manager" -> role = new ServiceManager();
            case "Service Technician" -> role = new ServiceTechnician();
            case "Production Manager" -> role = new ProductionManager();
            case "Quality Inspector" -> role = new QualityInspector();
            default -> {
                JOptionPane.showMessageDialog(null, "Could not create role for user.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        if (username.isBlank() || password.isBlank()) {
            JOptionPane.showMessageDialog(null, "Username/Password cannot be blank.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Update backend
        selectedOrganization.getUsers().createUser(selectedEmployee, username, password, role);
        
        // Notify + refresh
        JOptionPane.showMessageDialog(null, "Successfully created user!", "Success", JOptionPane.INFORMATION_MESSAGE);
        Component[] panelStack = workArea.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 2];
        ManageUsersJPanel mujp = (ManageUsersJPanel) lastPanel;
        mujp.refreshTable(); // Update table
    }//GEN-LAST:event_btnCreateActionPerformed

    private void tblOrganizationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrganizationsMouseClicked
        // Validate selected organization
        int selectedRow = tblOrganizations.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblOrganizations.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select an organization from the left table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Organization selectedOrg = (Organization) tblOrganizations.getValueAt(selectedRow, 0);
        if (selectedOrg == null) {
            JOptionPane.showMessageDialog(null, "Failed to get organization.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        this.selectedOrganization = selectedOrg;
        
        refreshEmployees();
        refreshCombo();
    }//GEN-LAST:event_tblOrganizationsMouseClicked

    private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeesMouseClicked
        // Validate selected employee
        int selectedRow = tblEmployees.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblEmployees.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select an employee from the top table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Employee selectedEmp = (Employee) tblEmployees.getValueAt(selectedRow, 0);
        if (selectedEmp == null) {
            JOptionPane.showMessageDialog(null, "Failed to get employee.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        this.selectedEmployee = selectedEmp;
    }//GEN-LAST:event_tblEmployeesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTable tblOrganizations;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void refreshOrganizations() {
        DefaultTableModel model = (DefaultTableModel) tblOrganizations.getModel();
        
        model.setRowCount(0);
        
        Object[] row = new Object[1];
        
        row[0] = organization;
        
        model.addRow(row);
        
        for (Organization o : organization.getCompany().getOrganizations().getOrganizations()) {
            row = new Object[1];
            
            row[0] = o;
            
            model.addRow(row);
        }
    }
    
    private void refreshEmployees() {
        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        
        model.setRowCount(0);
        
        for (Employee e : selectedOrganization.getEmployees().getEmployees()) {
            Object[] row = new Object[1];
            
            row[0] = e;
            
            model.addRow(row);
        }
    }

    private void refreshCombo() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbRole.getModel();
        
        model.removeAllElements();
        
        cmbRole.setEnabled(false);
        switch (selectedOrganization) {
            case AdminOrganization ao -> model.addElement("Admin");
            case LogisticsOrganization lo -> model.addElement("Logistics Coordinator");
            case WarehousingOrganization wo -> model.addElement("Warehouse Clerk");
            case SalesOrganization sao -> {
                model.addElement("Sales Representative");
                model.addElement("Customer Service Representative");
                cmbRole.setEnabled(true);
            }
            case ServiceOrganization seo -> {
                model.addElement("Service Manager");
                model.addElement("Service Technician");
                cmbRole.setEnabled(true);
            }
            case ProductionOrganization po -> model.addElement("Production Manager");
            case QualityAssuranceOrganization qao -> model.addElement("Quality Inspector");
            case default -> {}
        }
    }
}
