/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import Business.Ecosystem.Ecosystem;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.User.User;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ajay Alamuri
 */
public class ManageOrganizations extends javax.swing.JPanel {

    // ATTRIBUTES
    AdminOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    
    /**
     * Creates new form ManageOrganizations
     */
    public ManageOrganizations(JPanel csp, User usr, AdminOrganization org, Ecosystem system) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        
        initComponents();
        lblTitle.setText(this.organization.getCompany().getName() + " Organizations");
        
        refreshTable();
        populateCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganizations = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblOrganization = new javax.swing.JLabel();
        cmbOrganization = new javax.swing.JComboBox<>();
        btnView = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Company Name> Organizations");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 130, -1));

        tblOrganizations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "# of Employees", "# of Upcoming Tasks", "# of Completed Tasks"
            }
        ));
        jScrollPane1.setViewportView(tblOrganizations);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 610, 280));

        btnDelete.setText("Delete Selected Organization");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 200, -1));

        btnCreate.setText("Create Organization");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 140, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 160, -1));

        lblName.setText("New Organization Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 390, 140, -1));

        lblOrganization.setText("New Organization Type:");
        add(lblOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 140, -1));

        add(cmbOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 160, -1));

        btnView.setText("View >>>");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        // Validate selected organization
        int selectedRow = tblOrganizations.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblOrganizations.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select an organization from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Organization selectedOrganization = (Organization) tblOrganizations.getValueAt(selectedRow, 1);
        if (selectedOrganization == null) {
            JOptionPane.showMessageDialog(null, "Failed to delete organization.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (selectedOrganization instanceof AdminOrganization admins) {
            JOptionPane.showMessageDialog(null, "Cannot delete organization you are currently part of.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Remove in backend
        organization.getCompany().getOrganizations().removeOrganization(selectedOrganization);
        
        refreshTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        // Validate organization type + name
        String name = txtName.getText();
        if (name.isBlank()) {
            JOptionPane.showMessageDialog(null, "Organization name cannot be blank.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        OrganizationDirectory orgs = organization.getCompany().getOrganizations();
        int selectedIndex = cmbOrganization.getSelectedIndex();
        if (selectedIndex < 0 || selectedIndex > cmbOrganization.getItemCount()) {
            JOptionPane.showMessageDialog(null, "Please select an organization type from the combo box.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            switch(selectedIndex) {
                case 0 -> orgs.createSalesOrganization(name);
                case 1 -> orgs.createServiceOrganization(name);
                case 2 -> orgs.createLogisticsOrganization(name);
                case 3 -> orgs.createWarehousingOrganization(name);
                case 4 -> orgs.createProductionOrganization(name);
                case 5 -> orgs.createQualityAssuranceOrganization(name);
                default -> {}
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(null, "Successfully created organization!", "Success", JOptionPane.INFORMATION_MESSAGE);
        refreshTable();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        // Validate selected organization
        int selectedRow = tblOrganizations.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblOrganizations.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select an organization from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Organization selectedOrganization = (Organization) tblOrganizations.getValueAt(selectedRow, 1);
        if (selectedOrganization == null) {
            JOptionPane.showMessageDialog(null, "Failed to delete organization.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Load organization update page
        UpdateOrganizations uojp = new UpdateOrganizations(workArea, user, organization, business);
        this.workArea.add(uojp, "UpdateOrganizations");
        ((CardLayout) this.workArea.getLayout()).next(workArea);
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cmbOrganization;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblOrganizations;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrganizations.getModel();
        
        model.setRowCount(0);
        
        Object[] row = new Object[5];
        row[0] = organization.getID();
        row[1] = organization;
        row[2] = organization.getEmployees().getEmployees().size();
        row[3] = "N/A";
        row[4] = "N/A";
        
        model.addRow(row);
        
        for (Organization o : organization.getCompany().getOrganizations().getOrganizations()) {
            row = new Object[5];
            
            row[0] = o.getID();
            row[1] = o;
            row[2] = o.getEmployees().getEmployees().size();
            row[3] = o.getInTasks().getTasks().size();
            row[4] = o.getOutTasks().getTasks().size();
            
            model.addRow(row);
        }
    }

    private void populateCombo() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbOrganization.getModel();
        
        model.removeAllElements();
        
        model.addElement("Sales");
        model.addElement("Service");
        model.addElement("Logistics");
        model.addElement("Warehouse");
        model.addElement("Production");
        model.addElement("QA");
    }
}
