/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import Business.Ecosystem.Ecosystem;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.User.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ajay Alamuri
 */
public class ManageUsersJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    AdminOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    
    /**
     * Creates new form ManageUsersJPanel
     */
    public ManageUsersJPanel(JPanel csp, User usr, AdminOrganization org, Ecosystem system) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        
        initComponents();
        lblTitle.setText(this.organization.getCompany().getName() + " Users");
        
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Company Name> Users");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 130, -1));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Role", "Name", "Organization"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 610, 280));

        btnDelete.setText("Delete Selected User");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 200, -1));

        btnCreate.setText("Create User >>>");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 120, -1));

        btnView.setText("View >>>");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to previous page
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Delete selected user

        // Validate selected organization
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblUsers.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select a user from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        User selectedUser = (User) tblUsers.getValueAt(selectedRow, 2);
        Organization selectedOrganization = (Organization) tblUsers.getValueAt(selectedRow, 3);
        if (selectedUser == null || selectedOrganization == null) {
            JOptionPane.showMessageDialog(null, "Failed to delete user.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (selectedUser.getID() == user.getID()) {
            JOptionPane.showMessageDialog(null, "Cannot delete yourself.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Remove in backend
        selectedOrganization.getUsers().removeUser(selectedUser);
        
        // Notify + refresh
        JOptionPane.showMessageDialog(null, "Successfully deleted user!", "Success", JOptionPane.INFORMATION_MESSAGE);
        refreshTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // Load user creation page
        CreateUsersJPanel cujp = new CreateUsersJPanel(workArea, user, organization, business);
        this.workArea.add(cujp, "CreateUsers");
        ((CardLayout) this.workArea.getLayout()).next(workArea);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // Load user detailed view page

        // Validate selected user
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblUsers.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select a user from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        User selectedUser = (User) tblUsers.getValueAt(selectedRow, 2);
        Organization selectedOrganization = (Organization) tblUsers.getValueAt(selectedRow, 3);
        if (selectedUser == null || selectedOrganization == null) {
            JOptionPane.showMessageDialog(null, "Failed to get user.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Load user update page
        UpdateUsersJPanel uujp = new UpdateUsersJPanel(workArea, user, organization, business, selectedUser, selectedOrganization);
        this.workArea.add(uujp, "UpdateUsers");
        ((CardLayout) this.workArea.getLayout()).next(workArea);
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables

    public void refreshTable() {
        // Fill table with necessary info
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        
        model.setRowCount(0);
        
        for (User u : organization.getUsers().getUsers()) {
            Object[] row = new Object[4];
            
            row[0] = u.getUsername();
            row[1] = u.getRole();
            row[2] = u;
            row[3] = organization;
            
            model.addRow(row);
        }
        
        for (Organization org : organization.getCompany().getOrganizations().getOrganizations()) {
            for (User u : org.getUsers().getUsers()) {
                Object[] row = new Object[4];

                row[0] = u.getUsername();
                row[1] = u.getRole();
                row[2] = u;
                row[3] = org;
                
                model.addRow(row);
            }
        }
    }
}
