/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import Business.Ecosystem.Ecosystem;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.People.Employee;
import Business.People.Person;
import Business.User.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ajay Alamuri
 */
public class ManageEmployeesJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    AdminOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    
    /**
     * Creates new form ManageEmployeesJPanel
     */
    public ManageEmployeesJPanel(JPanel csp, User usr, AdminOrganization org, Ecosystem system) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        
        initComponents();
        lblTitle.setText(this.organization.getCompany().getName() + " Employees");
        
        refreshTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblOrganization = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrganizations = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Company Name> Employees");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 130, -1));

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Organization"
            }
        ));
        jScrollPane1.setViewportView(tblEmployees);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 610, 280));

        btnDelete.setText("Delete Selected Employee");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 200, -1));

        btnCreate.setText("Add Employee");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 140, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 160, -1));

        lblName.setText("New Employee Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 130, -1));

        lblOrganization.setText("Organization:");
        add(lblOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 90, -1));

        btnView.setText("View >>>");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, -1));

        tblOrganizations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Organization"
            }
        ));
        jScrollPane2.setViewportView(tblOrganizations);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 340, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        // Validate selected organization
        int selectedRow = tblEmployees.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblEmployees.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select an employee from the top table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Employee selectedEmployee = (Employee) tblEmployees.getValueAt(selectedRow, 1);
        Organization selectedOrganization = (Organization) tblEmployees.getValueAt(selectedRow, 2);
        if (selectedEmployee == null || selectedOrganization == null) {
            JOptionPane.showMessageDialog(null, "Failed to delete employee.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (selectedEmployee.getID() == user.getEmployee().getID()) {
            JOptionPane.showMessageDialog(null, "Cannot delete yourself.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Remove in backend
        selectedOrganization.getEmployees().removeEmployee(selectedEmployee);
        JOptionPane.showMessageDialog(null, "Successfully deleted employee!", "Success", JOptionPane.INFORMATION_MESSAGE);

        refreshTables();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:

        // Validate organization type + name
        String name = txtName.getText();
        if (name.isBlank()) {
            JOptionPane.showMessageDialog(null, "Employee name cannot be blank.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int selectedRow = tblOrganizations.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblOrganizations.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select an organization from the bottom table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Organization selectedOrganization = (Organization) tblOrganizations.getValueAt(selectedRow, 0);
        if (selectedOrganization == null) {
            JOptionPane.showMessageDialog(null, "Failed to get organization.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Update in backend
        Person p = new Person(name);
        selectedOrganization.getEmployees().createEmployee(p);

        // Notify + refresh
        JOptionPane.showMessageDialog(null, "Successfully added employee!", "Success", JOptionPane.INFORMATION_MESSAGE);
        refreshTables();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:

        // Validate selected organization
        int selectedRow = tblEmployees.getSelectedRow();
        if (selectedRow < 0 || selectedRow > tblEmployees.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Please select an employee from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Employee selectedEmployee = (Employee) tblEmployees.getValueAt(selectedRow, 1);
        Organization selectedOrganization = (Organization) tblEmployees.getValueAt(selectedRow, 2);
        if (selectedEmployee == null) {
            JOptionPane.showMessageDialog(null, "Failed to get employee.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Load organization update page
        UpdateEmployeesJPanel uejp = new UpdateEmployeesJPanel(workArea, user, organization, business, selectedEmployee, selectedOrganization);
        this.workArea.add(uejp, "UpdateEmployees");
        ((CardLayout) this.workArea.getLayout()).next(workArea);
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTable tblOrganizations;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    public void refreshTables() {
        refreshEmployees();
        refreshOrganizations();
    }

    private void refreshEmployees() {
        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        
        model.setRowCount(0);
        
        for (Employee e : organization.getEmployees().getEmployees()) {
            Object[] row = new Object[3];
            
            row[0] = e.getID();
            row[1] = e;
            row[2] = organization;
            
            model.addRow(row);
        }
        
        for (Organization org : organization.getCompany().getOrganizations().getOrganizations()) {
            for (Employee e : org.getEmployees().getEmployees()) {
                Object[] row = new Object[3];
                
                row[0] = e.getID();
                row[1] = e;
                row[2] = org;

                model.addRow(row);
            }
        }
    }

    private void refreshOrganizations() {
        DefaultTableModel model = (DefaultTableModel) tblOrganizations.getModel();
        
        model.setRowCount(0);
        
        Object[] row = new Object[1];
        
        row[0] = organization;
        
        model.addRow(row);
        
        for (Organization org : organization.getCompany().getOrganizations().getOrganizations()) {
            
            row[0] = org;
        
            model.addRow(row);
        }
    }
}
