/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import Business.Ecosystem.Ecosystem;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.People.Employee;
import Business.User.User;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ajay Alamuri
 */
public class UpdateEmployeesJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    AdminOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    Employee selectedEmployee;
    Organization selectedOrganization;
    
    /**
     * Creates new form UpdateEmployeesJPanel
     */
    public UpdateEmployeesJPanel(JPanel csp, User usr, AdminOrganization org, Ecosystem system, Employee emp, Organization orgs) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        this.selectedEmployee = emp;
        this.selectedOrganization = orgs;
        
        initComponents();
        this.lblTitle.setText(selectedEmployee.getPerson().getName() + " Update");
        
        refreshFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblOrganization = new javax.swing.JLabel();
        txtOrganization = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 130, -1));

        lblID.setText("Employee ID:");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 80, 30));

        txtID.setEditable(false);
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 110, 30));

        lblName.setText("Employee Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 100, 30));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 110, 30));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Employee Name> Update");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        lblOrganization.setText("Organization:");
        add(lblOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 80, 30));

        txtOrganization.setEditable(false);
        add(txtOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        // Field validation
        String name = txtName.getText();
        if (name.isBlank()) {
            JOptionPane.showMessageDialog(null, "Employee name cannot be blank", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Update in backend
        selectedEmployee.getPerson().setName(name);

        // Update previous page table
        Component[] panelStack = workArea.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 2];
        ManageEmployeesJPanel mejp = (ManageEmployeesJPanel) lastPanel;
        mejp.refreshTables(); // Update table

        // Notify and refresh
        JOptionPane.showMessageDialog(null, "Successfully updated employee name!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrganization;
    // End of variables declaration//GEN-END:variables

    private void refreshFields() {
        txtOrganization.setText(selectedOrganization.getName());
        txtID.setText(String.valueOf(selectedEmployee.getID()));
        txtName.setText(selectedEmployee.getPerson().getName());
    }
}
