/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import Business.Ecosystem.Ecosystem;
import Business.Organization.Organization;
import Business.People.Employee;
import Business.User.User;
import Business.WorkTaskQueue.WorkTask;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ajay Alamuri
 */
public class UpdateOrganizations extends javax.swing.JPanel {

    // ATTRIBUTES
    Organization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    
    /**
     * Creates new form UpdateOrganizations
     */
    public UpdateOrganizations(JPanel csp, User usr, Organization org, Ecosystem system) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        
        initComponents();
        lblTitle.setText(this.organization.getName() + " Update");
        
        refreshFields();
        populateTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Update");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 130, -1));

        lblID.setText("ID:");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 30, 30));

        txtID.setEditable(false);
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 30));

        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 30));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, 30));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "User Accounts"
            }
        ));
        jScrollPane3.setViewportView(tblUsers);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 440, 250));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Employees"
            }
        ));
        jScrollPane4.setViewportView(tblEmployees);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 440, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        // Field validation
        String name = txtName.getText();
        if (name.isBlank()) {
            JOptionPane.showMessageDialog(null, "Organization name cannot be blank", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Update in backend
        organization.setName(name);
        
        // Notify and refresh
        JOptionPane.showMessageDialog(null, "Successfully updated organization name!", "Success", JOptionPane.INFORMATION_MESSAGE);
        refreshFields();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void refreshFields() {
        txtID.setText(String.valueOf(organization.getID()));
        txtName.setText(organization.getName());
    }

    private void populateTables() {
        populateUsers();
        populateEmployees();
    }

    private void populateUsers() {
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        
        model.setRowCount(0);
        
        for (User u : organization.getUsers().getUsers()) {
            Object[] row = new Object[1];
            
            row[0] = u.getUsername();
            
            model.addRow(row);
        }
    }

    private void populateEmployees() {
        DefaultTableModel model = (DefaultTableModel) tblEmployees.getModel();
        
        model.setRowCount(0);
        
        for (Employee e : organization.getEmployees().getEmployees()) {
            Object[] row = new Object[1];
            
            row[0] = e.getPerson().getName();
            
            model.addRow(row);
        }
    }
}
