package UserInterface.Admin;

import Business.Organization.Organization;
import Business.Ecosystem.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrganization;
import Business.User.User;
import Business.WorkTaskQueue.WorkTask;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Ajay Alamuri
 */
public class ViewReportsJPanel extends javax.swing.JPanel {

    // ATTRIBUTES
    Enterprise company;
    JPanel workArea;
    User user;
    Ecosystem business;
    AdminOrganization organization;
    
    /**
     * Creates new form ViewReportsJPanel
     */
    public ViewReportsJPanel(JPanel csp, User usr, AdminOrganization org, Ecosystem system, Enterprise ent) {
        this.company = ent;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        this.organization = org;
        
        initComponents();
        lblTitle.setText(ent.getName() + " Reports");
        
        refreshOrgCombo();
        refreshUserTaskTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        cmbOrganization = new javax.swing.JComboBox<>();
        lblOrganization = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganizations = new javax.swing.JTable();
        lblUser = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 130, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Company Name> Reports");
        lblTitle.setMaximumSize(new java.awt.Dimension(650, 600));
        lblTitle.setMinimumSize(new java.awt.Dimension(650, 600));
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));

        cmbOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrganizationActionPerformed(evt);
            }
        });
        add(cmbOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, -1));

        lblOrganization.setText("Organization:");
        add(lblOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, 20));

        tblOrganizations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Task Type", "# Waiting/In Progress", "# Completed"
            }
        ));
        jScrollPane1.setViewportView(tblOrganizations);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 590, 110));

        lblUser.setText("Users:");
        add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 80, 20));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Organization", "Employee Name", "Role", "# of Tasks Completed", "# of Tasks Created"
            }
        ));
        jScrollPane2.setViewportView(tblUsers);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 590, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Return to previous page
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationActionPerformed
        // Fill table with relevant information
        
        // Selection validation
        int selectedIndex = cmbOrganization.getSelectedIndex();
        if (selectedIndex < 0 || selectedIndex > cmbOrganization.getItemCount()) {
            JOptionPane.showMessageDialog(null, "Please select a valid organization.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String orgName = (String) cmbOrganization.getItemAt(selectedIndex);
        if (orgName == null || orgName.isBlank()) {
            JOptionPane.showMessageDialog(null, "Organization name is invalid.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Get correct organization
        Organization selectedOrg = null;
        for (Organization org : company.getOrganizations().getOrganizations()) {
            if (org.getName().equals(orgName)) selectedOrg = org;
        }
        if (selectedOrg == null) {
            JOptionPane.showMessageDialog(null, "Failed to find selected organization.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Refresh table with tasks
        refreshOrgTaskTable(selectedOrg);
    }//GEN-LAST:event_cmbOrganizationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbOrganization;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTable tblOrganizations;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
    
    private void refreshOrgCombo() {
        // Fill combo with orgs
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbOrganization.getModel();
        
        model.removeAllElements();
        
        for (Organization org : company.getOrganizations().getOrganizations()) {
            model.addElement(org.getName());
        }
    }

    private void refreshOrgTaskTable(Organization selectedOrg) {
        // Refresh table with selected orgs task breakdown
        DefaultTableModel model = (DefaultTableModel) tblOrganizations.getModel();
        
        model.setRowCount(0);
        
        // Binds # waiting and # completed with Task type
        HashMap<String, ArrayList<Integer>> tasks = new HashMap();
        
        // Tasks waiting
        for (WorkTask task : selectedOrg.getInTasks().getTasks()) {
            
            String className = task.getClass().toString();
            int lastPeriod = className.lastIndexOf('.');
            className = className.substring(lastPeriod+1);
            
            ArrayList<Integer> values = tasks.get(className);
            if (values == null) {
                values = new ArrayList();
                values.add(1);
                values.add(0);
            } else {
                int current = values.get(0);
                values.set(0, current+1);
            }
            
            tasks.put(className, values);
        }
        
        // Tasks completed
        for (WorkTask task : selectedOrg.getOutTasks().getTasks()) {
            
            String className = task.getClass().toString();
            int lastPeriod = className.lastIndexOf('.');
            className = className.substring(lastPeriod+1);
            
            ArrayList<Integer> values = tasks.get(className);
            if (values == null) {
                values = new ArrayList();
                values.add(0);
                values.add(1);
            } else {
                int complete = values.get(1);
                values.set(1, complete+1);
            }
            
            tasks.put(className, values);
        }
        
        // Fill table
        for(String cName : tasks.keySet()) {
            Object[] row = new Object[3];
            
            row[0] = cName;
            row[1] = tasks.get(cName).get(0);
            row[2] = tasks.get(cName).get(1);
            
            model.addRow(row);
        }
    }

    private void refreshUserTaskTable() {
        // Fill table with users + task completion/creation stats
        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
        
        model.setRowCount(0);
        
        // All users from company
        HashMap<User, Organization> users = new HashMap();
        for (User u : organization.getUsers().getUsers()) {
            users.put(u, organization);
        }
        for (Organization org : company.getOrganizations().getOrganizations()) {
            for (User u : org.getUsers().getUsers()) {
                users.put(u, org);
            }
        }
        
        // Fill table
        for (User selectedUser : users.keySet()) {
            Organization selectedOrg = users.get(selectedUser);
            
            // Get currently completed tasks
            int completed = 0;
            for (WorkTask task : selectedOrg.getOutTasks().getTasks()) {
                if (task.getAssignee() != null) {
                    if (task.getAssignee().getID() == selectedUser.getID()) completed++;
                }
            }

            Object[] row = new Object[5];

            row[0] = selectedOrg;
            row[1] = selectedUser.toString();
            row[2] = selectedUser.getRole().toString();
            row[3] = selectedOrg instanceof AdminOrganization ? "N/A" : completed;
            row[4] = selectedOrg instanceof AdminOrganization ? "N/A" : selectedUser.getTasksCreated();

            model.addRow(row);
        }
    }
}