/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Business.ConfigureABusiness;
import Business.Ecosystem.Ecosystem;
import Business.Ecosystem.Network;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.User.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ajay Alamuri
 */
public class MainJFrame extends javax.swing.JFrame {

    // ATTRIBUTES
    Ecosystem system;
    User loggedIn;
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        this.system = ConfigureABusiness.initialize();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeSplitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblEmployees = new javax.swing.JLabel();
        workAreaPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(800, 600));

        homeSplitPane.setDividerLocation(150);
        homeSplitPane.setMinimumSize(new java.awt.Dimension(100, 600));

        controlPanel.setBackground(new java.awt.Color(153, 255, 255));
        controlPanel.setMinimumSize(new java.awt.Dimension(150, 600));
        controlPanel.setPreferredSize(new java.awt.Dimension(150, 600));
        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setText("Username:");
        controlPanel.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 24));
        controlPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, -1));

        lblPassword.setText("Password:");
        controlPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 24));
        controlPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        controlPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, -1));

        lblEmployees.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmployees.setText("Employees");
        controlPanel.add(lblEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 40));

        homeSplitPane.setLeftComponent(controlPanel);

        workAreaPanel.setMinimumSize(new java.awt.Dimension(650, 600));
        workAreaPanel.setPreferredSize(new java.awt.Dimension(650, 600));
        workAreaPanel.setLayout(new java.awt.CardLayout());
        homeSplitPane.setRightComponent(workAreaPanel);

        getContentPane().add(homeSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Authenticate user, then load work area
        
        // Field validation for username and password
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        if (username.isBlank() || password.isBlank()) {
            JOptionPane.showMessageDialog(this, "Username/Password cannot be blank.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Authentication and login
        this.loggedIn = null;
        Organization o = null;
        for (User u : system.getSuperAdmins().getUsers()) {
            if (u.authenticate(username, password)) this.loggedIn = u;
            if (this.loggedIn != null) break;
        }
        for (Network net : system.getNetworks()) {
            for (Enterprise ent : net.getEnterprises().getEnterprises()) {
                for (User u : ent.getAdmins().getUsers().getUsers()) {
                    if (u.authenticate(username, password)) this.loggedIn = u;
                    if (this.loggedIn != null) break;
                }
                for (Organization org : ent.getOrganizations().getOrganizations()) {
                    for (User u : org.getUsers().getUsers()) {
                        if (u.authenticate(username, password)) {
                            this.loggedIn = u;
                            o = org;
                        }
                        if (this.loggedIn != null) break;
                    }
                    if (this.loggedIn != null) break;
                }
                if (this.loggedIn != null) break;
            }
            if (this.loggedIn != null) break;
        }
        
        if (this.loggedIn == null) {
            JOptionPane.showMessageDialog(this, "Failed to login with provided Username and Password. Please check and try again.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Successfully logged in!", "Success", JOptionPane.INFORMATION_MESSAGE);
        JPanel nextPage = this.loggedIn.getRole().createWorkArea(workAreaPanel, this.loggedIn, o, this.system);
        workAreaPanel.add(nextPage, "WorkArea");
        ((CardLayout) workAreaPanel.getLayout()).next(workAreaPanel);
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane homeSplitPane;
    private javax.swing.JLabel lblEmployees;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPanel workAreaPanel;
    // End of variables declaration//GEN-END:variables
}
