/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.QualityAssurance;

import Business.Ecosystem.Ecosystem;
import Business.Ecosystem.Network;
import Business.Enterprise.Enterprise;
import Business.Organization.LogisticsOrganization;
import Business.Organization.Organization;
import Business.Organization.ProductionOrganization;
import Business.Organization.QualityAssuranceOrganization;
import Business.User.User;
import Business.WorkTaskQueue.BuildPartTask;
import Business.WorkTaskQueue.InspectPartTask;
import Business.WorkTaskQueue.OrderStatus;
import Business.WorkTaskQueue.ProcessShipmentTask;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Meredith Molyneux
 */
/**
 * Panel dedicated to inspecting individual manufactured car components.
 *
 * @author Adaptive AI Collaborator
 */
public class InspectPartJPanel extends javax.swing.JPanel {

    // STRUCTURAL ATTRIBUTES
    private QualityAssuranceOrganization organization;
    private JPanel workArea;
    private User user;
    private Ecosystem business;
    private InspectPartTask task;

    /**
     * Creates new form InspectPartJPanel
     */
    public InspectPartJPanel(JPanel csp, User usr, QualityAssuranceOrganization org, Ecosystem system, InspectPartTask tsk) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        this.task = tsk;

        initComponents();
        lblTitle.setText(this.organization.getName() + " - Inspect Part Request");

        // Layout structures generated here natively by your IDE builder
        populateTaskDetails();
    }

    /**
     * Maps processing data from the Task entity into the Swing View fields
     */
    private void populateTaskDetails() {
        if (task != null) {
            // Using your exact requested mapping signatures
            txtPartName.setText(task.getPartName());
            txtPartSerial.setText(task.getPartTestingStatus());
            txtComments.setText(task.getMessage()); // Inherited from WorkTask

            txtPartName.setEditable(false);
            txtPartSerial.setEditable(false);

            if ("Approved".equalsIgnoreCase(task.getStatus()) || "Rejected".equalsIgnoreCase(task.getStatus())) {
                btnApprove.setEnabled(false);
                btnReject.setEnabled(false);
                txtComments.setEditable(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPartName = new javax.swing.JTextField();
        txtPartSerial = new javax.swing.JTextField();
        txtComments = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 153, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Inspect Part Request");

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnBack.setText("<<< BACK");
        btnBack.setToolTipText("");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblName.setText("Part Id");

        lblNumber.setText("Testing Status");

        jLabel3.setText("Review Comments");

        txtPartSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartSerialActionPerformed(evt);
            }
        });

        txtComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblNumber)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPartSerial)
                            .addComponent(txtPartName)
                            .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnApprove)
                        .addGap(67, 67, 67)
                        .addComponent(btnReject)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtPartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPartSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumber))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(btnReject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommentsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
    ProductionOrganization productionOrganization = findProductionOrganization();
    if (productionOrganization == null) {
        JOptionPane.showMessageDialog(this, "Production department could not be found.", "Production Unavailable", JOptionPane.ERROR_MESSAGE);
        return;
    }
    try {
        // 1. Create a rework/re-inspection task in the Production inbound queue
        BuildPartTask buildPartTask = productionOrganization.getInTasks().createBuildPartTask(user, task.getPart());
        buildPartTask.setMessage("REJECTED by Quality Control. Reason: " + txtComments.getText().trim());

        // FIXED: Use OrderStatus enum constant instead of raw String
        buildPartTask.setStatus(OrderStatus.QA_FAILED);

        // 2. Mark the current inspection task as FAILED/REJECTED
        // FIXED: Use OrderStatus enum constant instead of raw String
        task.setResult(OrderStatus.QA_FAILED);
        task.setMessage(txtComments.getText().trim());
        task.setAssignee(user);
        task.Complete();

        // 3. Move the original inspection task out of your current inbound queue
        organization.getInTasks().popTask(task);
        organization.getOutTasks().pushTask(task); // Keeps a record of THIS completed inspection

        // REMOVED STEP 4: Do not push buildPartTask to organization.getOutTasks()!

        // 5. Clear the inspector's active workspace slot
        if (user != null && user.getRole() instanceof Business.Roles.QualityInspector) {
            ((Business.Roles.QualityInspector) user.getRole()).setCurrentTask(null);
        }
        JOptionPane.showMessageDialog(this, "Components REJECTED. Sent back to Production for rework.", "Inspection Saved", JOptionPane.WARNING_MESSAGE);
        goBack();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error routing rejection to Production: " + e.getMessage(), "Routing Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        LogisticsOrganization logisticsOrganization = findLogisticsOrganization();
    if (logisticsOrganization == null) {
        JOptionPane.showMessageDialog(this, "Supplier Logistics could not be found.", "Logistics Unavailable", JOptionPane.ERROR_MESSAGE);
        return;
    }
    try {
        // 1. Create the new shipment task inside the Logistics inbound queue
        ProcessShipmentTask shipment = logisticsOrganization.getInTasks().createProcessShipmentTask(user, task.getPart());

        // 2. Update and complete the current inspection task
        // FIXED: Use OrderStatus enum constant instead of raw String
        task.setResult(OrderStatus.QA_PASSED);
        task.setMessage(txtComments.getText().trim());
        task.setAssignee(user);
        task.Complete();

        // 3. Move the original task out of your current inbound queue
        organization.getInTasks().popTask(task);
        organization.getOutTasks().pushTask(task); // Keeps a record of THIS completed inspection

        // REMOVED STEP 4: Do not push shipment task to organization.getOutTasks()!

        // 5. Clear user workspace slot
        if (user != null && user.getRole() instanceof Business.Roles.QualityInspector) {
            ((Business.Roles.QualityInspector) user.getRole()).setCurrentTask(null);
        }
        JOptionPane.showMessageDialog(this, "Components verified and marked as APPROVED. Routed to Logistics.", "Inspection Saved", JOptionPane.INFORMATION_MESSAGE);
        goBack();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error routing to Logistics: " + e.getMessage(), "Routing Error", JOptionPane.ERROR_MESSAGE);
    } 

    }//GEN-LAST:event_btnApproveActionPerformed

    private void txtPartSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartSerialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtComments;
    private javax.swing.JTextField txtPartName;
    private javax.swing.JTextField txtPartSerial;
    // End of variables declaration//GEN-END:variables

    private void goBack() {
        // 1. Remove this screen container from the common display hierarchy
        workArea.remove(this);

        // 2. Fetch the collection array of active view layers inside the workArea
        Component[] componentArray = workArea.getComponents();

        // 3. Inspect the top-most active layout panel beneath this one
        if (componentArray.length > 0) {
            Component previousComponent = componentArray[componentArray.length - 1];

            // If you are backing into the Active Backlog panel
            if (previousComponent instanceof UserInterface.QualityAssurance.QARequestQueue) {
                ((UserInterface.QualityAssurance.QARequestQueue) previousComponent).refreshTable();
                       }
        }

        // 4. Safely shift the CardLayout state engine view layer backwards
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }

    private LogisticsOrganization findLogisticsOrganization() {
        for (Network network : business.getNetworks()) {
            for (Enterprise enterprise
                    : network.getEnterprises().getEnterprises()) {
                for (Organization organization
                        : enterprise.getOrganizations().getOrganizations()) {
                    if (organization instanceof LogisticsOrganization) {
                        return (LogisticsOrganization) organization;
                    }
                }
            }
        }

        return null;
    }
    private ProductionOrganization findProductionOrganization() {
        for (Network network : business.getNetworks()) {
            for (Enterprise enterprise
                    : network.getEnterprises().getEnterprises()) {
                for (Organization organization
                        : enterprise.getOrganizations().getOrganizations()) {
                    if (organization instanceof ProductionOrganization) {
                        return (ProductionOrganization) organization;
                    }
                }
            }
        }

        return null;
    }

}
