/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.QualityAssurance;

import Business.Ecosystem.Ecosystem;
import Business.Ecosystem.Network;
import Business.Enterprise.DealershipEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Organization.Organization;
import Business.Organization.ProductionOrganization;
import Business.Organization.QualityAssuranceOrganization;
import Business.Organization.SalesOrganization;
import Business.User.User;
import Business.Vehicle.CustomVehicleOrder;
import Business.WorkTaskQueue.InspectCarBuildTask;
import Business.WorkTaskQueue.OrderStatus;
import Business.WorkTaskQueue.VehicleDeliveryTask;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Meredith Molyneux
 */
public class InspectNewCarBuildJPanel extends javax.swing.JPanel {
        QualityAssuranceOrganization organization;
        JPanel workArea;
        User user;
        Ecosystem business;
        InspectCarBuildTask task;
        private  DealershipEnterprise destinationDealership;
    /**
     * Creates new form InspectPartJPanel
     */
    public InspectNewCarBuildJPanel(JPanel csp, User usr, QualityAssuranceOrganization org, Ecosystem system, InspectCarBuildTask tsk) {
         this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        this.task =tsk;
        initComponents();
        lblTitle.setText(this.organization.getName() + "- Inspect Car Build");
         populateVehicleDetails();
        this.destinationDealership = destinationDealership;
    }
    /**
     * Populates vehicle metrics into the Swing fields and enforces screen read-only locks
     */
  private void populateVehicleDetails() {
        if (task != null) {
            txtCarId.setText(String.valueOf(task.getVIN()));

            if (task.getCustomOrder() != null) {
                txtCarDetails.setText(task.getCustomOrder().getVehicleDescription());
            } else {
                txtCarDetails.setText(task.getMake() + " " + task.getModel() + " " + task.getTrim());
            }

            txtComments.setText(task.getMessage() == null ? "" : task.getMessage());

            txtCarId.setEditable(false);
            txtCarDetails.setEditable(false);

            // Lock controls if the task is complete OR has already passed/failed QA
            if (task.isCompleted() || task.getStatus() == OrderStatus.QA_PASSED || task.getStatus() == OrderStatus.QA_FAILED) {
                btnApprove.setEnabled(false);
                btnReject.setEnabled(false);
                txtComments.setEditable(false);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCarId = new javax.swing.JTextField();
        txtCarDetails = new javax.swing.JTextField();
        txtComments = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 153, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Inspect Car Build");

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnBack.setText("<<< BACK");
        btnBack.setToolTipText("");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblName.setText("Car ID");

        lblNumber.setText("Car details");

        jLabel3.setText("Comments");

        txtComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblNumber)
                                    .addComponent(jLabel3))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCarId, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(txtCarDetails)
                                    .addComponent(txtComments)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(btnApprove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(btnReject)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtCarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lblNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(btnReject))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
     if (!(task instanceof Business.WorkTaskQueue.InspectCarBuildTask)) {
            JOptionPane.showMessageDialog(this, "Invalid task type for vehicle build approval.", "System Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Business.WorkTaskQueue.InspectCarBuildTask carBuildTask = (Business.WorkTaskQueue.InspectCarBuildTask) task;

        // 1. Find the Sales Organization safely
        SalesOrganization salesOrganization = findSalesOrganization();
        if (salesOrganization == null) {
            JOptionPane.showMessageDialog(this, "Sales Organization could not be found.", "Sales Unavailable", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            CustomVehicleOrder customOrder = carBuildTask.getCustomOrder();
            if (customOrder == null) {
                JOptionPane.showMessageDialog(this, "No valid custom order is associated with this vehicle build task.", "Data Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
 // 2. HARDCODED OBJECT LOOKUP: Locate the specific DealershipEnterprise reference
            DealershipEnterprise destinationDealership = null;

            // Loop through all enterprises in the system directory
            // (Note: Change 'business' to your exact EcoSystem variable name if needed, e.g., 'system' or 'ecoSystem')
            for (Network net : business.getNetworks()) {
            EnterpriseDirectory ed = net.getEnterprises();
            if (ed.findEnterprise(organization.getCompany().getID()) != null) {
                for (DealershipEnterprise de : ed.getDealerships())

                    if (destinationDealership != null) break;
                }
            }

            // 3. Verify that the enterprise reference was found in memory
            if (destinationDealership == null) {
                JOptionPane.showMessageDialog(this, "The hardcoded Dealership Enterprise could not be found in the system registry.", "Routing Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Verify that the enterprise reference was successfully resolved
            if (destinationDealership == null) {
                JOptionPane.showMessageDialog(this, "The target destination dealership could not be resolved from the system directory.", "Routing Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 4. Create the new vehicle delivery task inside the Sales inbound queue
            VehicleDeliveryTask delivery = salesOrganization.getInTasks().createVehicleDeliveryTask(user, customOrder, destinationDealership);

            // 5. Update and complete the current vehicle build inspection task
            carBuildTask.setStatus(OrderStatus.QA_PASSED);
            carBuildTask.setMessage(txtComments.getText().trim());
            carBuildTask.setAssignee(user);
            carBuildTask.Complete();

            // 6. Move the original task out of your current inbound queue
            organization.getInTasks().popTask(carBuildTask);
            organization.getOutTasks().pushTask(carBuildTask);

            // 7. Clear user workspace slot
            if (user != null && user.getRole() instanceof Business.Roles.QualityInspector) {
                ((Business.Roles.QualityInspector) user.getRole()).setCurrentTask(null);
            }

            JOptionPane.showMessageDialog(this, "Vehicle assembly APPROVED and cleared for Delivery!", "Audit Cleared", JOptionPane.INFORMATION_MESSAGE);
            goBack();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error routing vehicle to Sales: " + e.getMessage(), "Routing Error", JOptionPane.ERROR_MESSAGE);
            goBack();
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
          if (txtComments.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Audit rejection requires comprehensive deficiency descriptions.", "Input Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // CHANGED: Applying global Enum instead of raw string "Fail"
        task.setStatus(OrderStatus.QA_FAILED);
        task.setMessage(txtComments.getText().trim());
        task.setAssignee(user);
        task.Complete();

        if (user.getRole() instanceof Business.Roles.QualityInspector) {
            ((Business.Roles.QualityInspector) user.getRole()).setCurrentTask(null);
        }

        JOptionPane.showMessageDialog(this, "Vehicle FAILED audit metrics. Routed back to work floor modifications.", "Audit Rejection", JOptionPane.WARNING_MESSAGE);
        goBack();
    
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCarDetails;
    private javax.swing.JTextField txtCarId;
    private javax.swing.JTextField txtComments;
    // End of variables declaration//GEN-END:variables
   private void goBack() {
        workArea.remove(this);
        Component[] componentArray = workArea.getComponents();
        if (componentArray.length > 0) {
            Component previousComponent = componentArray[componentArray.length - 1];
            
            // Triggers a table refresh depending on which dashboard queue you backed out of
            if (previousComponent instanceof UserInterface.QualityAssurance.QARequestQueue) {
                ((UserInterface.QualityAssurance.QARequestQueue) previousComponent).refreshTable();
       
            }
        }
        
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }
       private SalesOrganization findSalesOrganization() {
        for (Network network : business.getNetworks()) {
            for (Enterprise enterprise
                    : network.getEnterprises().getEnterprises()) {
                for (Organization organization
                        : enterprise.getOrganizations().getOrganizations()) {
                    if (organization instanceof SalesOrganization) {
                        return (SalesOrganization) organization;
                    }
                }
            }
        }

        return null;
    }
    private ProductionOrganization findProductionOrganization() {
        for (Network network : business.getNetworks()) {
            for (Enterprise enterprise
                    : network.getEnterprises().getEnterprises()) {
                for (Organization organization
                        : enterprise.getOrganizations().getOrganizations()) {
                    if (organization instanceof ProductionOrganization) {
                        return (ProductionOrganization) organization;
                    }
                }
            }
        }

        return null;
    }
}
