/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.QualityAssurance;

import Business.Ecosystem.Ecosystem;
import Business.Ecosystem.Network;
import Business.Enterprise.DealershipEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.LogisticsOrganization;
import Business.Organization.Organization;
import Business.Organization.QualityAssuranceOrganization;
import Business.User.User;
import Business.WorkTaskQueue.InspectPartTask;
import Business.WorkTaskQueue.ProcessShipmentTask;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Meredith Molyneux
 */


/**
 * Panel dedicated to inspecting individual manufactured car components.
 * @author Adaptive AI Collaborator
 */
public class InspectPartJPanel extends javax.swing.JPanel {

    // STRUCTURAL ATTRIBUTES
    private QualityAssuranceOrganization organization;
    private JPanel workArea;
    private User user;
    private Ecosystem business;
    private InspectPartTask task;

    
    /**
     * Creates new form InspectPartJPanel
     */
    public InspectPartJPanel(JPanel csp, User usr, QualityAssuranceOrganization org, Ecosystem system, InspectPartTask tsk) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        this.task = tsk;

        initComponents();
        lblTitle.setText(this.organization.getName() + " - Inspect Part Request");
      
        
        // Layout structures generated here natively by your IDE builder
    
        populateTaskDetails();
    }

    /**
     * Maps processing data from the Task entity into the Swing View fields
     */
   private void populateTaskDetails() {
        if (task != null) {
            // Using your exact requested mapping signatures
            txtPartName.setText(task.getPartName());
            txtPartSerial.setText(task.getPartSerialNumber());
            txtComments.setText(task.getMessage()); // Inherited from WorkTask

            txtPartName.setEditable(false);
            txtPartSerial.setEditable(false);

            if ("Approved".equalsIgnoreCase(task.getStatus()) || "Rejected".equalsIgnoreCase(task.getStatus())) {
                btnApprove.setEnabled(false);
                btnReject.setEnabled(false);
                txtComments.setEditable(false);
            }
        }
    }

      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPartName = new javax.swing.JTextField();
        txtPartSerial = new javax.swing.JTextField();
        txtComments = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 153, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Inspect Part Request");

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnBack.setText("<<< BACK");
        btnBack.setToolTipText("");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblName.setText("Part Id");

        lblNumber.setText("Testing Status");

        jLabel3.setText("Review Comments");

        txtPartSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartSerialActionPerformed(evt);
            }
        });

        txtComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblNumber)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPartSerial)
                            .addComponent(txtPartName)
                            .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnApprove)
                        .addGap(67, 67, 67)
                        .addComponent(btnReject)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtPartName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPartSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumber))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(btnReject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommentsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
       if(txtComments.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please insert defect notes inside the comment field before rejecting.", "Input Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 1. Commit data updates to the task wrapper
    task.setResult("Fail");
    task.setMessage(txtComments.getText().trim());
    task.setAssignee(user); // Standard WorkTask inherited parameter assignment
    task.Complete();        // Flips parent boolean completed flag to true

    // 2. Perform the Enterprise Queue Shift
    // No explicit structural list copying needed anymore! The dashboard screens
    // will now automatically filter this item into your completed history panel
    // using the task.isCompleted() conditional check.

    // 3. Reset the QualityInspector assignment block state
    if (user != null && user.getRole() instanceof Business.Roles.QualityInspector) {
        ((Business.Roles.QualityInspector) user.getRole()).setCurrentTask(null);
    }

    JOptionPane.showMessageDialog(this, "Component marked as REJECTED.", "Inspection Saved", JOptionPane.INFORMATION_MESSAGE);
    goBack();

    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // 1. Commit data updates to the task wrapper
        
        LogisticsOrganization logisticsOrganization = null;
        DealershipEnterprise dealership = null;

        for (Network network : business.getNetworks()) {
            Enterprise ent = network.getEnterprises().findEnterprise(organization.getCompany().getID());
            if (ent != null) {
                for (Enterprise enterprise : network.getEnterprises().getEnterprises()) {
                    if (enterprise instanceof DealershipEnterprise) {
                        dealership = (DealershipEnterprise) enterprise;
                    }
                    for (Organization org : enterprise.getOrganizations().getOrganizations()) {
                        if (org instanceof LogisticsOrganization) {
                            logisticsOrganization = (LogisticsOrganization) org;
                        }
                    }
                } 
            }
        }
        
        if (logisticsOrganization == null || dealership == null) {
            JOptionPane.showMessageDialog(this, "Could not find Logistics organization or Dealership.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            ProcessShipmentTask pstask = logisticsOrganization.getInTasks().createProcessShipmentTask(user, task.getPart());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed to create delivery task, please retry.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        task.setResult("Pass");
        task.setMessage(txtComments.getText().trim());
        task.setAssignee(user);
        task.Complete(); // This flips the completed flag to true inside your shared WorkTask class

        // Clear user's role workspace slot so they can click a new assignment later
        if (user != null && user.getRole() instanceof Business.Roles.QualityInspector) {
            ((Business.Roles.QualityInspector) user.getRole()).setCurrentTask(null);
        }

        JOptionPane.showMessageDialog(this, "Component verified and marked as APPROVED, shipment sent to Logistics.", "Inspection Saved", JOptionPane.INFORMATION_MESSAGE);
        goBack();
   
    }//GEN-LAST:event_btnApproveActionPerformed

    private void txtPartSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartSerialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtComments;
    private javax.swing.JTextField txtPartName;
    private javax.swing.JTextField txtPartSerial;
    // End of variables declaration//GEN-END:variables

        private void goBack() {
        // 1. Remove this screen container from the common display hierarchy
        workArea.remove(this);

        // 2. Fetch the collection array of active view layers inside the workArea
        Component[] componentArray = workArea.getComponents();

        // 3. Inspect the top-most active layout panel beneath this one
        if (componentArray.length > 0) {
            Component previousComponent = componentArray[componentArray.length - 1];

            // If you are backing into the Active Backlog panel
            if (previousComponent instanceof UserInterface.QualityAssurance.QARequestQueue) {
                ((UserInterface.QualityAssurance.QARequestQueue) previousComponent).refreshTable();
            }
            // If you are backing into the Completed Logs panel
            else if (previousComponent instanceof UserInterface.QualityAssurance.QADoneQueue) {
                ((UserInterface.QualityAssurance.QADoneQueue) previousComponent).refreshCompletedTable();
            }
        }

        // 4. Safely shift the CardLayout state engine view layer backwards
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }
}