/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.QualityAssurance;

import Business.Ecosystem.Ecosystem;
import Business.Organization.QualityAssuranceOrganization;
import Business.User.User;
import Business.WorkTaskQueue.IssueRecallTask;
import javax.swing.JPanel;

/**
 *
 * @author Meredith Molyneux
 */
public class IssueRecallJPanel extends javax.swing.JPanel {
        QualityAssuranceOrganization organization;
        JPanel workArea;
        User user;
        Ecosystem business;
        IssueRecallTask task;
    /**
     * Creates new form InspectPartJPanel
     */
    public IssueRecallJPanel(JPanel csp, User usr, QualityAssuranceOrganization org, Ecosystem system, IssueRecallTask tsk) {
         this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        this.task =tsk;
        initComponents();
        lblTitle.setText(this.organization.getName() + "- Issue Recall");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Issue Recall");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
