/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.QualityAssurance;

import Business.Ecosystem.Ecosystem;
import Business.Organization.QualityAssuranceOrganization;
import Business.User.User;
import Business.WorkTaskQueue.WorkTask;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Meredith Molyneux
 */
public class QADoneQueue extends javax.swing.JPanel {
                  // ATTRIBUTES
    QualityAssuranceOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    /**
     * Creates new form WorkQueueJPanel
     */
    public QADoneQueue(JPanel csp, User usr, QualityAssuranceOrganization org, Ecosystem system) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        initComponents();
        lblTitle.setText(this.organization.getName() + " - Queue");
         refreshCompletedTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTasks = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Queue");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, -1));

        tblTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Task", "Assigned By", "Completed By", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblTasks);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 44, 610, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblTasks;
    // End of variables declaration//GEN-END:variables

    public void refreshCompletedTable() {
        DefaultTableModel model = (DefaultTableModel) tblTasks.getModel();
        model.setRowCount(0);

        for (WorkTask task : this.organization.getInTasks().getTasks()) {
            if (task.isCompleted()) {
                // FIX: Add the size block [4] here
                Object[] row = new Object[4];

                row[0] = task;
                row[1] = task.getAssigner();
                row[2] = (task.getAssignee() == null) ? "System" : task.getAssignee();

                if (task instanceof Business.WorkTaskQueue.InspectPartTask) {
                    String res = ((Business.WorkTaskQueue.InspectPartTask) task).getResult();
                    row[3] = "Pass".equalsIgnoreCase(res) ? "Approved" : "Rejected";
                }
                else if (task instanceof Business.WorkTaskQueue.InspectCarBuildTask) {
                    String res = ((Business.WorkTaskQueue.InspectCarBuildTask) task).getResult();
                    row[3] = "Pass".equalsIgnoreCase(res) ? "Approved" : "Rejected";
                } 
                else {
                    row[3] = "Complete";
                }

                model.addRow(row);
            }
        }
    }
}

