/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.QualityAssurance;

import Business.Ecosystem.Ecosystem;
import Business.Organization.QualityAssuranceOrganization;
import Business.Roles.QualityInspector;
import Business.User.User;
import Business.WorkTaskQueue.WorkTask;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Meredith Molyneux
 */
public class QARequestQueue extends javax.swing.JPanel {
                  // ATTRIBUTES
    QualityAssuranceOrganization organization;
    JPanel workArea;
    User user;
    Ecosystem business;
    /**
     * Creates new form WorkQueueJPanel
     */
    public QARequestQueue(JPanel csp, User usr, QualityAssuranceOrganization org, Ecosystem system) {
        this.organization = org;
        this.workArea = csp;
        this.user = usr;
        this.business = system;
        initComponents();
         lblTitle.setText(this.organization.getName() + " - Queue");
         refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTasks = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("<Org Name> Queue");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 418, 130, -1));

        tblTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Assigned By", "Assigned To", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblTasks);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 610, 300));

        btnAssign.setText("Assign To Me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        ((CardLayout) workArea.getLayout()).previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
int selectedRow = tblTasks.getSelectedRow();

    // Fix boundary safety checks to prevent IndexOutOfBounds exceptions
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select an unassigned task line from the table.", "Selection Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Safely extract the raw cell value
    Object cellObject = tblTasks.getValueAt(selectedRow, 0);
    WorkTask selectedTask = null;

    // TYPE-SAFETY CHECK: Ensure the table cell actually holds the WorkTask object
    if (cellObject instanceof WorkTask) {
        selectedTask = (WorkTask) cellObject;
    } else {
        // Fallback recovery if column 0 only contains an Integer/String primitive ID
        int taskId = Integer.parseInt(cellObject.toString());
        for (WorkTask t : this.organization.getInTasks().getTasks()) {
            if (t.getID() == taskId) {
                selectedTask = t;
                break;
            }
        }
    }
    // Structural validation guard checks
    if (selectedTask == null) {
        JOptionPane.showMessageDialog(this, "The system could not resolve the selected task reference identity.", "System Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (selectedTask.getAssignee() != null) {
        JOptionPane.showMessageDialog(this, "An employee is already handling this task. Please choose an open request.", "Assignment Conflict", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Safety cast for your user's specific workflow role properties
    if (user != null && user.getRole() instanceof QualityInspector) {
        QualityInspector inspectorRole = (QualityInspector) user.getRole();

        if (inspectorRole.getCurrentTask() != null) {
            JOptionPane.showMessageDialog(this, "You cannot assign a new task while your current assignment is still open.", "Workload Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Commit mutations to tracking variables across structural references
        inspectorRole.setCurrentTask(selectedTask);
        selectedTask.setAssignee(user);

        JOptionPane.showMessageDialog(this, "Task securely assigned! Proceed to the inspection panel.", "Assignment Confirmed", JOptionPane.INFORMATION_MESSAGE);
        refreshTable();

    } else {
        JOptionPane.showMessageDialog(this, "Your user profile does not possess valid QualityInspector structural authorization clearances.", "Access Denied", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblTasks;
    // End of variables declaration//GEN-END:variables

public void refreshTable() {
    DefaultTableModel model = (DefaultTableModel) tblTasks.getModel();
    model.setRowCount(0); // Clear table data

    // Grabs remaining active and unassigned work lines
    for (WorkTask task : this.organization.getInTasks().getTasks()) {
        if (!task.isCompleted()) {
            Object[] row = new Object[4];

            row[0] = task;               // Column 1: ID / Task Object reference
            row[1] = task.getAssigner(); // Column 3: Assigned By (Production Manager)
            row[2] = task.getAssignee() == null ? "Unassigned" : task.getAssignee(); // Column 4: Assigned To
            row[3] = task.getAssignee() == null ? "Waiting" : "In Progress";         // Column 5: Status

            model.addRow(row);
        }
    }
}
}
